/* Rank Rebels — homepage internationalization.
   Text-keyed runtime: each translatable element's English text is the key; values may contain
   inline markup (e.g. <span class="hl">). Strings with no translation gracefully stay English.
   Adds a language switcher, persists the choice, and sets <html lang>/<html dir> (RTL for Arabic). */
(function () {
  var LANGS = [
    { code: 'en', native: 'English',   dir: 'ltr' },
    { code: 'es', native: 'Español',   dir: 'ltr' },
    { code: 'zh', native: '中文',       dir: 'ltr' },
    { code: 'vi', native: 'Tiếng Việt', dir: 'ltr' },
    { code: 'tl', native: 'Tagalog',   dir: 'ltr' },
    { code: 'fr', native: 'Français',  dir: 'ltr' },
    { code: 'ar', native: 'العربية',    dir: 'rtl' }
  ];

  // English key -> { es, zh, vi, tl, fr, ar }
  var T = {
    // ---- nav ----
    'Services': { es:'Servicios', zh:'服务', vi:'Dịch vụ', tl:'Mga Serbisyo', fr:'Services', ar:'الخدمات' },
    'Process': { es:'Proceso', zh:'流程', vi:'Quy trình', tl:'Proseso', fr:'Processus', ar:'العملية' },
    'Areas': { es:'Zonas', zh:'服务地区', vi:'Khu vực', tl:'Mga Lugar', fr:'Régions', ar:'المناطق' },
    'Our Why': { es:'Nuestro porqué', zh:'我们的理念', vi:'Lý do của chúng tôi', tl:'Ang Aming Layunin', fr:'Notre raison d’être', ar:'لماذا نحن' },
    'Reviews': { es:'Reseñas', zh:'评价', vi:'Đánh giá', tl:'Mga Review', fr:'Avis', ar:'التقييمات' },
    'Blog': { es:'Blog', zh:'博客', vi:'Blog', tl:'Blog', fr:'Blog', ar:'المدوّنة' },
    'FAQ': { es:'Preguntas frecuentes', zh:'常见问题', vi:'Câu hỏi thường gặp', tl:'Mga FAQ', fr:'FAQ', ar:'الأسئلة الشائعة' },
    'Team login': { es:'Acceso del equipo', zh:'团队登录', vi:'Đăng nhập nhóm', tl:'Team login', fr:'Connexion équipe', ar:'دخول الفريق' },

    // ---- hero ----
    'Websites · SEO · Google Business Profile': { es:'Sitios web · SEO · Perfil de Google Business', zh:'网站 · SEO · Google 商家资料', vi:'Trang web · SEO · Hồ sơ Google Business', tl:'Mga Website · SEO · Google Business Profile', fr:'Sites web · SEO · Profil Google Business', ar:'مواقع · SEO · الملف التجاري على Google' },
    'When customers search,your business is the answer.': { es:'Cuando los clientes buscan,<br>tu negocio es la <span class="hl">respuesta</span>.', zh:'当客户搜索时，<br>你的企业就是<span class="hl">答案</span>。', vi:'Khi khách hàng tìm kiếm,<br>doanh nghiệp của bạn là <span class="hl">câu trả lời</span>.', tl:'Kapag naghahanap ang mga customer,<br>ang negosyo mo ang <span class="hl">sagot</span>.', fr:'Quand les clients cherchent,<br>votre entreprise est la <span class="hl">réponse</span>.', ar:'عندما يبحث العملاء،<br>تكون شركتك هي <span class="hl">الإجابة</span>.' },
    'We build fast, custom websites and help local businesses get found on Google, in the Map pack, and when people ask ChatGPT & AI for a recommendation.': { es:'Creamos sitios web rápidos y personalizados, y ayudamos a los negocios locales a aparecer en Google, en el paquete de mapas y cuando la gente le pide recomendaciones a ChatGPT y a la IA.', zh:'我们打造快速、定制的网站，帮助本地企业出现在 Google 搜索、地图栏，以及人们向 ChatGPT 和 AI 寻求推荐时。', vi:'Chúng tôi xây dựng các trang web nhanh, tùy chỉnh và giúp doanh nghiệp địa phương được tìm thấy trên Google, trong Map pack và khi mọi người hỏi ChatGPT & AI để được giới thiệu.', tl:'Gumagawa kami ng mabilis at custom na website at tinutulungan ang mga lokal na negosyo na matagpuan sa Google, sa Map pack, at kapag humihingi ng rekomendasyon ang mga tao sa ChatGPT at AI.', fr:'Nous créons des sites web rapides et sur mesure et aidons les entreprises locales à être trouvées sur Google, dans le pack local et quand les gens demandent une recommandation à ChatGPT et à l’IA.', ar:'نصمّم مواقع سريعة ومخصّصة ونساعد الشركات المحلية على الظهور في Google وفي حزمة الخرائط وعندما يطلب الناس توصية من ChatGPT والذكاء الاصطناعي.' },
    'Get your free audit →': { es:'Obtén tu auditoría gratis →', zh:'获取免费诊断 →', vi:'Nhận đánh giá miễn phí →', tl:'Kunin ang libreng audit →', fr:'Obtenez votre audit gratuit →', ar:'احصل على تدقيقك المجاني →' },
    'See how it works': { es:'Mira cómo funciona', zh:'了解运作方式', vi:'Xem cách hoạt động', tl:'Tingnan kung paano ito gumagana', fr:'Voir comment ça marche', ar:'شاهد كيف يعمل' },

    'Built to be found on': { es:'Diseñado para que te encuentren en', zh:'专为被发现而打造', vi:'Được xây dựng để được tìm thấy trên', tl:'Ginawa para matagpuan sa', fr:'Conçu pour être trouvé sur', ar:'مُصمّم ليُعثر عليه على' },

    // ---- problem ----
    'The problem': { es:'El problema', zh:'问题所在', vi:'Vấn đề', tl:'Ang Problema', fr:'Le problème', ar:'المشكلة' },
    'Your website is your first impression': { es:'Tu sitio web es tu <span class="hl">primera impresión</span>', zh:'你的网站就是你的<span class="hl">第一印象</span>', vi:'Trang web của bạn là <span class="hl">ấn tượng đầu tiên</span>', tl:'Ang website mo ang iyong <span class="hl">unang impresyon</span>', fr:'Votre site web est votre <span class="hl">première impression</span>', ar:'موقعك هو <span class="hl">انطباعك الأول</span>' },
    'When a customer Googles your name, what do they find? A pro that earns the call, or a reason to call your competitor?': { es:'Cuando un cliente busca tu nombre en Google, ¿qué encuentra? ¿Un profesional que se gana la llamada, o un motivo para llamar a tu competencia?', zh:'当客户在 Google 上搜索你的名字时，他们会看到什么？一个值得致电的专业商家，还是一个转而联系竞争对手的理由？', vi:'Khi khách hàng tìm tên bạn trên Google, họ thấy gì? Một chuyên gia đáng để gọi, hay một lý do để gọi cho đối thủ của bạn?', tl:'Kapag ni-Google ng customer ang pangalan mo, ano ang makikita nila? Isang propesyonal na karapat-dapat tawagan, o dahilan para tawagan ang kakumpitensya mo?', fr:'Quand un client cherche votre nom sur Google, que trouve-t-il ? Un pro qui mérite l’appel, ou une raison d’appeler votre concurrent ?', ar:'عندما يبحث العميل عن اسمك على Google، ماذا يجد؟ محترفًا يستحق الاتصال، أم سببًا للاتصال بمنافسك؟' },
    'Outdated design': { es:'Diseño anticuado', zh:'设计过时', vi:'Thiết kế lỗi thời', tl:'Lumang disenyo', fr:'Design dépassé', ar:'تصميم قديم' },
    'Slow load time': { es:'Carga lenta', zh:'加载缓慢', vi:'Tải chậm', tl:'Mabagal mag-load', fr:'Chargement lent', ar:'بطء التحميل' },
    'Invisible on Google & AI': { es:'Invisible en Google e IA', zh:'在 Google 和 AI 上不可见', vi:'Vô hình trên Google & AI', tl:'Hindi nakikita sa Google at AI', fr:'Invisible sur Google et l’IA', ar:'غير مرئي على Google والذكاء الاصطناعي' },
    'Weak Google Business presence': { es:'Presencia débil en Google Business', zh:'Google 商家展示薄弱', vi:'Hiện diện Google Business yếu', tl:'Mahinang presensya sa Google Business', fr:'Présence Google Business faible', ar:'حضور ضعيف على Google Business' },
    'Not mobile-friendly': { es:'No apto para móviles', zh:'不适配手机', vi:'Không thân thiện với di động', tl:'Hindi mobile-friendly', fr:'Pas adapté au mobile', ar:'غير متوافق مع الجوال' },
    'The DIY template trap': { es:'La trampa de las plantillas “hazlo tú mismo”', zh:'自助模板陷阱', vi:'Cái bẫy mẫu tự làm', tl:'Ang bitag ng DIY template', fr:'Le piège des modèles « à faire soi-même »', ar:'فخّ القوالب الجاهزة' },

    // ---- services ----
    'What we do': { es:'Lo que hacemos', zh:'我们的服务', vi:'Chúng tôi làm gì', tl:'Ang Ginagawa Namin', fr:'Ce que nous faisons', ar:'ما نقوم به' },
    'Build it. Rank it. Manage it.': { es:'Constrúyelo. Posiciónalo. <span class="hl">Gestiónalo.</span>', zh:'搭建。排名。<span class="hl">管理。</span>', vi:'Xây dựng. Xếp hạng. <span class="hl">Quản lý.</span>', tl:'Gawin. I-rank. <span class="hl">Pamahalaan.</span>', fr:'Créer. Classer. <span class="hl">Gérer.</span>', ar:'نبنيه. نرفع ترتيبه. <span class="hl">نديره.</span>' },
    'Custom Builds': { es:'Sitios a medida', zh:'定制开发', vi:'Thiết kế riêng', tl:'Custom na Build', fr:'Sites sur mesure', ar:'تصميمات مخصّصة' },
    'Hand-crafted, lightning-fast sites that match your brand. Mobile-first, conversion-focused, launch-ready in days.': { es:'Sitios hechos a mano y ultrarrápidos que reflejan tu marca. Pensados para móvil, enfocados en conversión y listos para lanzar en días.', zh:'手工打造、闪电般快速且契合你品牌的网站。移动优先、专注转化，数天内即可上线。', vi:'Trang web được làm thủ công, nhanh như chớp và hợp với thương hiệu của bạn. Ưu tiên di động, tập trung chuyển đổi, sẵn sàng ra mắt trong vài ngày.', tl:'Mga site na gawa nang maayos, napakabilis, at bagay sa iyong brand. Mobile-first, nakatuon sa conversion, at handa nang i-launch sa loob ng ilang araw.', fr:'Des sites faits main, ultra-rapides et fidèles à votre marque. Pensés mobile d’abord, axés sur la conversion, prêts à être lancés en quelques jours.', ar:'مواقع مصنوعة بعناية وفائقة السرعة تعكس علامتك التجارية. مُصمّمة للجوال أولاً، تركّز على التحويل، وجاهزة للإطلاق خلال أيام.' },
    'SEO & AI Search': { es:'SEO y búsqueda con IA', zh:'SEO 与 AI 搜索', vi:'SEO & Tìm kiếm AI', tl:'SEO at AI Search', fr:'SEO & recherche IA', ar:'SEO وبحث الذكاء الاصطناعي' },
    'Engineered to climb Google and show up when customers ask ChatGPT and AI search for a recommendation.': { es:'Diseñado para escalar en Google y aparecer cuando los clientes le piden una recomendación a ChatGPT y a la búsqueda con IA.', zh:'专为攀升 Google 排名而打造，并在客户向 ChatGPT 和 AI 搜索寻求推荐时出现。', vi:'Được thiết kế để leo hạng trên Google và xuất hiện khi khách hàng hỏi ChatGPT và tìm kiếm AI để được giới thiệu.', tl:'Ginawa para umakyat sa Google at lumitaw kapag humihingi ng rekomendasyon ang mga customer sa ChatGPT at AI search.', fr:'Conçu pour grimper sur Google et apparaître quand les clients demandent une recommandation à ChatGPT et à la recherche IA.', ar:'مُصمّم للصعود في Google والظهور عندما يطلب العملاء توصية من ChatGPT وبحث الذكاء الاصطناعي.' },
    'Google Business Profile': { es:'Perfil de Google Business', zh:'Google 商家资料', vi:'Hồ sơ Google Business', tl:'Google Business Profile', fr:'Profil Google Business', ar:'الملف التجاري على Google' },
    'We set up and manage your Google listing to drive calls, directions, and reviews, and own the local Map pack.': { es:'Configuramos y gestionamos tu ficha de Google para generar llamadas, indicaciones y reseñas, y dominar el paquete de mapas local.', zh:'我们为你设置并管理 Google 商家信息，带来来电、导航和评价，并占据本地地图栏。', vi:'Chúng tôi thiết lập và quản lý hồ sơ Google của bạn để tạo cuộc gọi, chỉ đường và đánh giá, và làm chủ Map pack địa phương.', tl:'Ise-set up at pamamahalaan namin ang iyong Google listing para magdala ng tawag, direksyon, at review, at angkinin ang lokal na Map pack.', fr:'Nous créons et gérons votre fiche Google pour générer des appels, des itinéraires et des avis, et dominer le pack local.', ar:'نُنشئ ونُدير بطاقتك على Google لجلب المكالمات والاتجاهات والتقييمات والسيطرة على حزمة الخرائط المحلية.' },

    // ---- statband labels ----
    'of people Google you before they call': { es:'de las personas te buscan en Google antes de llamar', zh:'的人在致电前会先 Google 你', vi:'số người tìm bạn trên Google trước khi gọi', tl:'ng mga tao ang nag-Google sa iyo bago tumawag', fr:'des gens vous cherchent sur Google avant d’appeler', ar:'من الناس يبحثون عنك على Google قبل الاتصال' },
    'to launch, not months': { es:'para lanzar, no meses', zh:'即可上线，而非数月', vi:'để ra mắt, không phải hàng tháng', tl:'para mag-launch, hindi buwan', fr:'pour lancer, pas des mois', ar:'للإطلاق، وليس أشهرًا' },
    'monthly, or save with a term': { es:'mensual, o ahorra con un plazo', zh:'按月付费，或选择长期更省', vi:'hàng tháng, hoặc tiết kiệm với gói dài hạn', tl:'buwanan, o makatipid sa term', fr:'au mois, ou économisez avec un engagement', ar:'شهريًا، أو وفّر باشتراك لمدة' },
    'optimized from day one': { es:'optimizado desde el primer día', zh:'从第一天起优化', vi:'tối ưu từ ngày đầu', tl:'optimisado mula sa unang araw', fr:'optimisé dès le premier jour', ar:'مُحسّن من اليوم الأول' },

    // ---- process ----
    'Your new website in 4 simple steps': { es:'Tu nuevo sitio web en <span class="hl">4 sencillos pasos</span>', zh:'<span class="hl">4 个简单步骤</span>打造你的新网站', vi:'Trang web mới của bạn trong <span class="hl">4 bước đơn giản</span>', tl:'Ang bagong website mo sa <span class="hl">4 na simpleng hakbang</span>', fr:'Votre nouveau site en <span class="hl">4 étapes simples</span>', ar:'موقعك الجديد في <span class="hl">4 خطوات بسيطة</span>' },
    'Free audit': { es:'Auditoría gratis', zh:'免费诊断', vi:'Đánh giá miễn phí', tl:'Libreng audit', fr:'Audit gratuit', ar:'تدقيق مجاني' },
    'We review your site and search presence and show you exactly where leads are leaking out.': { es:'Revisamos tu sitio y tu presencia en buscadores y te mostramos exactamente por dónde se te escapan los clientes.', zh:'我们审查你的网站和搜索表现，准确指出潜在客户从哪里流失。', vi:'Chúng tôi rà soát trang web và sự hiện diện tìm kiếm của bạn và chỉ ra chính xác nơi khách hàng tiềm năng đang rò rỉ.', tl:'Sinusuri namin ang site at search presence mo at ipinapakita kung saan eksakto natutulo ang mga lead.', fr:'Nous analysons votre site et votre présence dans les recherches et vous montrons exactement où vous perdez des clients.', ar:'نراجع موقعك وحضورك في البحث ونوضّح لك بالضبط أين تتسرّب العملاء المحتملون.' },
    'Design & build': { es:'Diseño y desarrollo', zh:'设计与搭建', vi:'Thiết kế & xây dựng', tl:'Disenyo at build', fr:'Conception & création', ar:'التصميم والبناء' },
    'We design and build your custom, conversion-focused site, fast.': { es:'Diseñamos y construimos tu sitio personalizado y enfocado en conversión, rápido.', zh:'我们快速设计并搭建专注转化的定制网站。', vi:'Chúng tôi thiết kế và xây dựng trang web tùy chỉnh, tập trung chuyển đổi của bạn, nhanh chóng.', tl:'Dinidisenyo at binubuo namin ang iyong custom, conversion-focused na site, mabilis.', fr:'Nous concevons et créons votre site sur mesure, axé conversion, rapidement.', ar:'نصمّم ونبني موقعك المخصّص الذي يركّز على التحويل، بسرعة.' },
    'Optimize': { es:'Optimización', zh:'优化', vi:'Tối ưu', tl:'I-optimize', fr:'Optimisation', ar:'التحسين' },
    'SEO, speed, and tracking dialed in for Google and AI search, then we go live.': { es:'Ajustamos SEO, velocidad y seguimiento para Google y la búsqueda con IA, y luego lo publicamos.', zh:'为 Google 和 AI 搜索调校 SEO、速度和数据追踪，然后正式上线。', vi:'Tinh chỉnh SEO, tốc độ và theo dõi cho Google và tìm kiếm AI, rồi chúng tôi cho ra mắt.', tl:'I-aayos ang SEO, bilis, at tracking para sa Google at AI search, tapos go live na.', fr:'SEO, vitesse et suivi réglés pour Google et la recherche IA, puis mise en ligne.', ar:'نضبط SEO والسرعة والتتبّع لِ*Google* وبحث الذكاء الاصطناعي، ثم ننشر الموقع.' },
    'Grow': { es:'Crecimiento', zh:'增长', vi:'Phát triển', tl:'Lumago', fr:'Croissance', ar:'النمو' },
    'Ongoing tuning and monthly reporting so your rankings and leads keep climbing.': { es:'Ajustes continuos e informes mensuales para que tus posiciones y clientes sigan creciendo.', zh:'持续调整与每月报告，让你的排名和客户不断攀升。', vi:'Tinh chỉnh liên tục và báo cáo hàng tháng để thứ hạng và khách hàng của bạn tiếp tục tăng.', tl:'Tuluy-tuloy na pag-tune at buwanang ulat para patuloy na umakyat ang ranking at lead mo.', fr:'Optimisation continue et rapports mensuels pour que vos classements et prospects continuent de grimper.', ar:'ضبط مستمر وتقارير شهرية كي يستمرّ ترتيبك وعملاؤك في الصعود.' },

    // ---- why ----
    'Why RankRebels': { es:'Por qué RankRebels', zh:'为何选择 RankRebels', vi:'Vì sao chọn RankRebels', tl:'Bakit RankRebels', fr:'Pourquoi RankRebels', ar:'لماذا RankRebels' },
    'The modern alternative to bloated agencies': { es:'La alternativa moderna a las <span class="hl">agencias infladas</span>', zh:'臃肿代理机构的<span class="hl">现代替代方案</span>', vi:'Giải pháp hiện đại thay cho <span class="hl">các agency cồng kềnh</span>', tl:'Ang modernong alternatibo sa <span class="hl">malalaking ahensya</span>', fr:'L’alternative moderne aux <span class="hl">agences trop lourdes</span>', ar:'البديل العصري <span class="hl">للوكالات المتضخّمة</span>' },

    // ---- reviews ----
    'What clients say': { es:'Lo que dicen los clientes', zh:'客户怎么说', vi:'Khách hàng nói gì', tl:'Ang Sabi ng mga Kliyente', fr:'Ce que disent les clients', ar:'ماذا يقول العملاء' },
    'Businesses that joined the Rebellion': { es:'Negocios que se unieron a la <span class="hl">Rebelión</span>', zh:'加入<span class="hl">反叛军</span>的企业', vi:'Những doanh nghiệp đã gia nhập <span class="hl">Cuộc nổi dậy</span>', tl:'Mga negosyong sumali sa <span class="hl">Rebelyon</span>', fr:'Des entreprises qui ont rejoint la <span class="hl">Rébellion</span>', ar:'شركات انضمّت إلى <span class="hl">التمرّد</span>' },

    // ---- values ----
    'Who we are': { es:'Quiénes somos', zh:'我们是谁', vi:'Chúng tôi là ai', tl:'Sino Kami', fr:'Qui nous sommes', ar:'من نحن' },
    'We put small businesses where they belong: on top.': { es:'Ponemos a los pequeños negocios donde merecen estar: <span class="hl">en la cima.</span>', zh:'我们让小企业站到应有的位置：<span class="hl">顶端。</span>', vi:'Chúng tôi đưa các doanh nghiệp nhỏ đến nơi họ thuộc về: <span class="hl">đỉnh cao.</span>', tl:'Inilalagay namin ang maliliit na negosyo kung nasaan dapat sila: <span class="hl">sa tuktok.</span>', fr:'Nous mettons les petites entreprises là où elles méritent : <span class="hl">au sommet.</span>', ar:'نضع الشركات الصغيرة حيث تستحق: <span class="hl">في القمّة.</span>' },
    'We Rebel with Purpose': { es:'Nos rebelamos con Propósito', zh:'我们以「使命」反叛', vi:'Chúng tôi nổi dậy bằng Mục đích', tl:'Naghihimagsik kami nang may Layunin', fr:'Nous nous rebellons avec Détermination', ar:'نتمرّد بهدف' },
    'We Rebel with Grit': { es:'Nos rebelamos con Determinación', zh:'我们以「韧劲」反叛', vi:'Chúng tôi nổi dậy bằng Sự kiên cường', tl:'Naghihimagsik kami nang may Tatag', fr:'Nous nous rebellons avec Ténacité', ar:'نتمرّد بعزيمة' },
    'We Rebel with Honesty': { es:'Nos rebelamos con Honestidad', zh:'我们以「诚实」反叛', vi:'Chúng tôi nổi dậy bằng Sự trung thực', tl:'Naghihimagsik kami nang may Katapatan', fr:'Nous nous rebellons avec Honnêteté', ar:'نتمرّد بصدق' },
    'We Rebel with Ownership': { es:'Nos rebelamos con Compromiso', zh:'我们以「担当」反叛', vi:'Chúng tôi nổi dậy bằng Tinh thần trách nhiệm', tl:'Naghihimagsik kami nang may Pananagutan', fr:'Nous nous rebellons avec Responsabilité', ar:'نتمرّد بالمسؤولية' },
    'We Rebel with Vision': { es:'Nos rebelamos con Visión', zh:'我们以「远见」反叛', vi:'Chúng tôi nổi dậy bằng Tầm nhìn', tl:'Naghihimagsik kami nang may Pananaw', fr:'Nous nous rebellons avec Vision', ar:'نتمرّد برؤية' },

    // ---- faq ----
    'Questions, answered': { es:'Preguntas, <span class="hl">respondidas</span>', zh:'问题，<span class="hl">已解答</span>', vi:'Câu hỏi, <span class="hl">đã giải đáp</span>', tl:'Mga tanong, <span class="hl">nasagot</span>', fr:'Vos questions, <span class="hl">nos réponses</span>', ar:'أسئلة <span class="hl">مُجاب عنها</span>' },
    'How fast can you build my website?': { es:'¿Qué tan rápido pueden crear mi sitio web?', zh:'你们能多快做好我的网站？', vi:'Bạn xây dựng website cho tôi nhanh thế nào?', tl:'Gaano kabilis ninyo magagawa ang website ko?', fr:'En combien de temps créez-vous mon site ?', ar:'ما مدى سرعة بناء موقعي؟' },
    'Do you optimize for Google and AI search?': { es:'¿Optimizan para Google y la búsqueda con IA?', zh:'你们会针对 Google 和 AI 搜索进行优化吗？', vi:'Bạn có tối ưu cho Google và tìm kiếm AI không?', tl:'Ino-optimize ba ninyo para sa Google at AI search?', fr:'Optimisez-vous pour Google et la recherche IA ?', ar:'هل تُحسّنون للظهور في Google وبحث الذكاء الاصطناعي؟' },
    'Is there a commitment?': { es:'¿Hay algún compromiso de permanencia?', zh:'需要签约承诺吗？', vi:'Có ràng buộc cam kết không?', tl:'May commitment ba?', fr:'Y a-t-il un engagement ?', ar:'هل هناك التزام؟' },
    'Who do you work with?': { es:'¿Con quién trabajan?', zh:'你们与谁合作？', vi:'Bạn làm việc với ai?', tl:'Kanino kayo nakikipagtulungan?', fr:'Avec qui travaillez-vous ?', ar:'مع مَن تعملون؟' },
    'What does it cost?': { es:'¿Cuánto cuesta?', zh:'费用是多少？', vi:'Chi phí là bao nhiêu?', tl:'Magkano ang gastos?', fr:'Combien ça coûte ?', ar:'كم التكلفة؟' },

    // ---- contact ----
    'Tell us about your business and we\'ll send a free, no-pressure audit of your site and search presence within 24 hours.': { es:'Cuéntanos sobre tu negocio y te enviaremos una auditoría gratuita y sin compromiso de tu sitio y tu presencia en buscadores en menos de 24 horas.', zh:'告诉我们你的业务，我们将在 24 小时内免费、无压力地为你的网站和搜索表现做一份诊断。', vi:'Hãy cho chúng tôi biết về doanh nghiệp của bạn và chúng tôi sẽ gửi đánh giá miễn phí, không áp lực về trang web và sự hiện diện tìm kiếm trong vòng 24 giờ.', tl:'Sabihin sa amin ang tungkol sa negosyo mo at magpapadala kami ng libre, walang-presyur na audit ng site at search presence mo sa loob ng 24 oras.', fr:'Parlez-nous de votre entreprise et nous vous enverrons un audit gratuit et sans engagement de votre site et de votre présence en ligne sous 24 heures.', ar:'أخبِرنا عن نشاطك التجاري وسنرسل لك تدقيقًا مجانيًا وبلا أي ضغط لموقعك وحضورك في البحث خلال 24 ساعة.' },
    'Your name': { es:'Tu nombre', zh:'你的姓名', vi:'Tên của bạn', tl:'Pangalan mo', fr:'Votre nom', ar:'اسمك' },
    'Business name': { es:'Nombre del negocio', zh:'企业名称', vi:'Tên doanh nghiệp', tl:'Pangalan ng negosyo', fr:'Nom de l’entreprise', ar:'اسم النشاط التجاري' },
    'Email': { es:'Correo electrónico', zh:'电子邮箱', vi:'Email', tl:'Email', fr:'E-mail', ar:'البريد الإلكتروني' },
    'Phone (optional)': { es:'Teléfono (opcional)', zh:'电话（可选）', vi:'Điện thoại (tùy chọn)', tl:'Telepono (opsyonal)', fr:'Téléphone (facultatif)', ar:'الهاتف (اختياري)' },
    'What do you need? (new site, redesign, more leads…)': { es:'¿Qué necesitas? (sitio nuevo, rediseño, más clientes…)', zh:'你需要什么？（新网站、改版、更多客户……）', vi:'Bạn cần gì? (trang mới, thiết kế lại, thêm khách hàng…)', tl:'Ano ang kailangan mo? (bagong site, redesign, mas maraming lead…)', fr:'De quoi avez-vous besoin ? (nouveau site, refonte, plus de clients…)', ar:'ماذا تحتاج؟ (موقع جديد، إعادة تصميم، عملاء أكثر…)' },
    'Get my free audit →': { es:'Quiero mi auditoría gratis →', zh:'获取我的免费诊断 →', vi:'Nhận đánh giá miễn phí của tôi →', tl:'Kunin ang libreng audit ko →', fr:'Obtenir mon audit gratuit →', ar:'احصل على تدقيقي المجاني →' },
    '✓ Got it. We\'ll be in touch within 24 hours with your free audit.': { es:'✓ Recibido. Nos pondremos en contacto en menos de 24 horas con tu auditoría gratis.', zh:'✓ 已收到。我们将在 24 小时内联系你并提供免费诊断。', vi:'✓ Đã nhận. Chúng tôi sẽ liên hệ trong vòng 24 giờ kèm đánh giá miễn phí của bạn.', tl:'✓ Natanggap. Makikipag-ugnayan kami sa loob ng 24 oras kasama ang libreng audit mo.', fr:'✓ Bien reçu. Nous vous contacterons sous 24 heures avec votre audit gratuit.', ar:'✓ تمّ الاستلام. سنتواصل معك خلال 24 ساعة مع تدقيقك المجاني.' },

    // ---- faq answers ----
    'Days, not months. Once we have your content and goals, we design, build, and optimize a custom site fast. Most launches happen within days.': { es:'Días, no meses. En cuanto tengamos tu contenido y tus objetivos, diseñamos, construimos y optimizamos un sitio personalizado rápidamente. La mayoría se lanzan en pocos días.', zh:'是几天，而不是几个月。拿到你的内容和目标后，我们会快速设计、搭建并优化定制网站。大多数项目可在数天内上线。', vi:'Vài ngày, không phải vài tháng. Khi đã có nội dung và mục tiêu của bạn, chúng tôi thiết kế, xây dựng và tối ưu một trang web tùy chỉnh nhanh chóng. Hầu hết ra mắt trong vài ngày.', tl:'Araw, hindi buwan. Kapag nasa amin na ang content at mga layunin mo, mabilis naming dinidisenyo, binubuo, at ino-optimize ang custom na site. Karamihan ay nila-launch sa loob ng ilang araw.', fr:'Des jours, pas des mois. Une fois votre contenu et vos objectifs en main, nous concevons, créons et optimisons un site sur mesure rapidement. La plupart sont lancés en quelques jours.', ar:'أيام، وليس أشهرًا. بمجرد حصولنا على محتواك وأهدافك، نصمّم ونبني ونحسّن موقعًا مخصّصًا بسرعة. معظم المواقع تُطلق خلال أيام.' },
    'Yes. SEO is built in from day one. Every site is engineered to rank on Google and to surface when customers ask ChatGPT and other AI search tools for a recommendation.': { es:'Sí. El SEO está integrado desde el primer día. Cada sitio se diseña para posicionar en Google y aparecer cuando los clientes le piden una recomendación a ChatGPT y a otras herramientas de búsqueda con IA.', zh:'是的。SEO 从第一天起就内置其中。每个网站都经过设计，可在 Google 上排名，并在客户向 ChatGPT 等 AI 搜索工具寻求推荐时出现。', vi:'Có. SEO được tích hợp ngay từ ngày đầu. Mỗi trang web được thiết kế để xếp hạng trên Google và xuất hiện khi khách hàng hỏi ChatGPT và các công cụ tìm kiếm AI khác để được giới thiệu.', tl:'Oo. Naka-build in ang SEO mula sa unang araw. Bawat site ay ginawa para mag-rank sa Google at lumitaw kapag humihingi ng rekomendasyon ang mga customer sa ChatGPT at iba pang AI search tools.', fr:'Oui. Le SEO est intégré dès le premier jour. Chaque site est conçu pour se classer sur Google et apparaître quand les clients demandent une recommandation à ChatGPT et aux autres outils de recherche IA.', ar:'نعم. تحسين محركات البحث مُدمج منذ اليوم الأول. كل موقع مُصمّم ليتصدّر في Google ويظهر عندما يطلب العملاء توصية من ChatGPT وأدوات البحث بالذكاء الاصطناعي الأخرى.' },
    'Your choice. Go month-to-month, or save with a 1- or 2-year plan that includes our bumper-to-bumper warranty: unlimited support and adjustments while you\'re with us. Great SEO compounds over time, so a longer term keeps us fully invested in your growth, but there\'s no surprise lock-in, and you always own your site.': { es:'Tú decides. Paga mes a mes, o ahorra con un plan de 1 o 2 años que incluye nuestra garantía total: soporte y ajustes ilimitados mientras estés con nosotros. Un buen SEO se acumula con el tiempo, así que un plazo más largo nos mantiene comprometidos con tu crecimiento, pero sin ataduras sorpresa, y el sitio siempre es tuyo.', zh:'由你决定。可按月付费，或选择 1 年或 2 年方案更省钱，并享有我们的全包保修：合作期间提供无限支持与调整。优秀的 SEO 会随时间累积，因此更长的合约让我们全力投入你的增长，但没有任何意外绑定，而且网站始终归你所有。', vi:'Tùy bạn. Trả theo tháng, hoặc tiết kiệm với gói 1 hoặc 2 năm bao gồm bảo hành toàn diện: hỗ trợ và điều chỉnh không giới hạn khi bạn đồng hành cùng chúng tôi. SEO tốt tích lũy theo thời gian, nên gói dài hạn giúp chúng tôi toàn tâm với sự phát triển của bạn, nhưng không có ràng buộc bất ngờ, và bạn luôn sở hữu trang web của mình.', tl:'Ikaw ang bahala. Mag month-to-month, o makatipid sa 1- o 2-taong plano na may kasamang bumper-to-bumper warranty: walang-limitasyong suporta at adjustment habang kasama ka namin. Ang magandang SEO ay lumalakas sa paglipas ng panahon, kaya ang mas mahabang termino ay nagpapanatili sa aming pamumuhunan sa paglago mo, pero walang sorpresang lock-in, at lagi mong pag-aari ang site mo.', fr:'À vous de choisir. Au mois, ou économisez avec un forfait de 1 ou 2 ans incluant notre garantie tout compris : support et ajustements illimités pendant toute la durée. Un bon SEO se renforce avec le temps, donc un engagement plus long nous garde pleinement investis dans votre croissance, mais sans piège, et votre site vous appartient toujours.', ar:'القرار لك. ادفع شهريًا، أو وفّر مع خطة سنة أو سنتين تشمل ضماننا الشامل: دعم وتعديلات غير محدودة طوال فترة تعاملك معنا. تحسين محركات البحث الجيّد يتراكم مع الوقت، لذا تبقينا المدة الأطول ملتزمين تمامًا بنموّك، دون أي ارتباط مفاجئ، ويظل موقعك ملكك دائمًا.' },
    'Local businesses that refuse to blend in: service providers, shops, and growing brands that want a custom site that ranks and converts.': { es:'Negocios locales que se niegan a pasar desapercibidos: prestadores de servicios, tiendas y marcas en crecimiento que quieren un sitio personalizado que posicione y convierta.', zh:'拒绝泯然众人的本地企业：服务商、店铺和成长中的品牌，他们想要一个能排名、能转化的定制网站。', vi:'Các doanh nghiệp địa phương không chịu hòa lẫn: nhà cung cấp dịch vụ, cửa hàng và thương hiệu đang phát triển muốn một trang web tùy chỉnh có thứ hạng và chuyển đổi.', tl:'Mga lokal na negosyong ayaw maging karaniwan: mga service provider, tindahan, at lumalagong brand na gustong magkaroon ng custom na site na nagra-rank at nagko-convert.', fr:'Des entreprises locales qui refusent de se fondre dans la masse : prestataires de services, commerces et marques en croissance qui veulent un site sur mesure qui se classe et convertit.', ar:'الشركات المحلية التي ترفض أن تكون عادية: مزوّدو الخدمات والمتاجر والعلامات النامية التي تريد موقعًا مخصّصًا يتصدّر ويحقّق التحويلات.' },
    'A one-time build/onboarding fee plus a simple monthly management plan. Start with a free, no-pressure audit and we\'ll scope it to your business.': { es:'Una tarifa única de creación/incorporación más un sencillo plan mensual de gestión. Empieza con una auditoría gratuita y sin compromiso y la ajustamos a tu negocio.', zh:'一次性的建站/启动费用，加上简单的按月管理方案。先从免费、无压力的诊断开始，我们会根据你的业务量身定制。', vi:'Một khoản phí xây dựng/khởi tạo một lần cộng với gói quản lý hàng tháng đơn giản. Bắt đầu bằng một đánh giá miễn phí, không áp lực và chúng tôi sẽ điều chỉnh cho doanh nghiệp của bạn.', tl:'Isang beses na build/onboarding fee kasama ang simpleng buwanang management plan. Magsimula sa libre at walang-presyur na audit at i-a-angkop namin ito sa negosyo mo.', fr:'Des frais uniques de création/intégration plus un simple forfait de gestion mensuel. Commencez par un audit gratuit et sans engagement, et nous l’adapterons à votre entreprise.', ar:'رسوم بناء/إعداد لمرة واحدة بالإضافة إلى خطة إدارة شهرية بسيطة. ابدأ بتدقيق مجاني وبلا ضغط وسنُفصّله حسب نشاطك التجاري.' },

    // ---- comparison table ----
    'Traditional Agency': { es:'Agencia tradicional', zh:'传统代理机构', vi:'Agency truyền thống', tl:'Tradisyonal na Ahensya', fr:'Agence traditionnelle', ar:'وكالة تقليدية' },
    'DIY Builder': { es:'Editor “hazlo tú mismo”', zh:'自助建站工具', vi:'Công cụ tự làm', tl:'DIY Builder', fr:'Outil « à faire soi-même »', ar:'أداة جاهزة' },
    'Truly custom design': { es:'Diseño realmente personalizado', zh:'真正的定制设计', vi:'Thiết kế thực sự tùy chỉnh', tl:'Tunay na custom na disenyo', fr:'Design vraiment sur mesure', ar:'تصميم مخصّص فعلاً' },
    'Time to launch': { es:'Tiempo de lanzamiento', zh:'上线时间', vi:'Thời gian ra mắt', tl:'Oras bago mag-launch', fr:'Délai de lancement', ar:'وقت الإطلاق' },
    'SEO included': { es:'SEO incluido', zh:'包含 SEO', vi:'Bao gồm SEO', tl:'Kasama ang SEO', fr:'SEO inclus', ar:'يشمل SEO' },
    'Built for AI search': { es:'Diseñado para la búsqueda con IA', zh:'专为 AI 搜索打造', vi:'Xây dựng cho tìm kiếm AI', tl:'Ginawa para sa AI search', fr:'Conçu pour la recherche IA', ar:'مُصمّم لبحث الذكاء الاصطناعي' },
    'Invested in your growth': { es:'Comprometidos con tu crecimiento', zh:'投入于你的增长', vi:'Đầu tư vào sự phát triển của bạn', tl:'Nakatuon sa paglago mo', fr:'Investis dans votre croissance', ar:'ملتزمون بنموّك' },
    '✓ Built for you': { es:'<span class="yes">✓ Hecho para ti</span>', zh:'<span class="yes">✓ 为你打造</span>', vi:'<span class="yes">✓ Dành riêng cho bạn</span>', tl:'<span class="yes">✓ Ginawa para sa iyo</span>', fr:'<span class="yes">✓ Fait pour vous</span>', ar:'<span class="yes">✓ صُمّم لك</span>' },
    'Sometimes': { es:'A veces', zh:'有时', vi:'Đôi khi', tl:'Minsan', fr:'Parfois', ar:'أحيانًا' },
    'Templates only': { es:'Solo plantillas', zh:'仅限模板', vi:'Chỉ mẫu có sẵn', tl:'Mga template lang', fr:'Modèles uniquement', ar:'قوالب فقط' },
    'Days': { es:'Días', zh:'数天', vi:'Vài ngày', tl:'Mga araw', fr:'Quelques jours', ar:'أيام' },
    'Weeks to months': { es:'De semanas a meses', zh:'数周至数月', vi:'Vài tuần đến vài tháng', tl:'Linggo hanggang buwan', fr:'Des semaines à des mois', ar:'أسابيع إلى أشهر' },
    'Your nights & weekends': { es:'Tus noches y fines de semana', zh:'你的夜晚和周末', vi:'Đêm và cuối tuần của bạn', tl:'Mga gabi at weekend mo', fr:'Vos soirées et week-ends', ar:'لياليك وعطلاتك الأسبوعية' },
    '✓ From day one': { es:'<span class="yes">✓ Desde el primer día</span>', zh:'<span class="yes">✓ 从第一天起</span>', vi:'<span class="yes">✓ Ngay từ ngày đầu</span>', tl:'<span class="yes">✓ Mula sa unang araw</span>', fr:'<span class="yes">✓ Dès le premier jour</span>', ar:'<span class="yes">✓ من اليوم الأول</span>' },
    'Costly add-on': { es:'Extra costoso', zh:'高价附加项', vi:'Tiện ích đắt đỏ', tl:'Magastos na add-on', fr:'Option coûteuse', ar:'إضافة مكلفة' },
    'On your own': { es:'Por tu cuenta', zh:'全靠自己', vi:'Tự lo', tl:'Ikaw mag-isa', fr:'Par vous-même', ar:'بمفردك' },
    'Rarely': { es:'Rara vez', zh:'很少', vi:'Hiếm khi', tl:'Bihira', fr:'Rarement', ar:'نادرًا' },
    '✓ Ongoing partnership': { es:'<span class="yes">✓ Alianza continua</span>', zh:'<span class="yes">✓ 持续合作</span>', vi:'<span class="yes">✓ Hợp tác lâu dài</span>', tl:'<span class="yes">✓ Tuluy-tuloy na partnership</span>', fr:'<span class="yes">✓ Partenariat continu</span>', ar:'<span class="yes">✓ شراكة مستمرّة</span>' },
    'Project, then gone': { es:'Proyecto y adiós', zh:'项目做完就走人', vi:'Xong dự án là biến mất', tl:'Proyekto, tapos wala na', fr:'Le projet, puis plus rien', ar:'مشروع ثم يختفون' },

    // ---- values intro + paragraphs + manifesto ----
    'We don\'t just rank websites. We Rebel, with purpose, grit, honesty, ownership, and vision. It\'s how we fight for the underdogs, the overlooked, and the businesses that are better than their Google ranking shows.': { es:'No solo posicionamos sitios web. Nos rebelamos, con propósito, determinación, honestidad, compromiso y visión. Así luchamos por los que parten en desventaja, los ignorados y los negocios que valen más de lo que muestra su posición en Google.', zh:'我们不只是为网站做排名。我们以使命、韧劲、诚实、担当和远见去反叛。我们正是这样为弱者、被忽视者，以及那些比其 Google 排名更优秀的企业而战。', vi:'Chúng tôi không chỉ xếp hạng website. Chúng tôi nổi dậy — bằng mục đích, sự kiên cường, trung thực, trách nhiệm và tầm nhìn. Đó là cách chúng tôi chiến đấu cho những kẻ yếu thế, bị bỏ quên, và những doanh nghiệp giỏi hơn thứ hạng Google của họ.', tl:'Hindi lang kami nagra-rank ng mga website. Naghihimagsik kami — nang may layunin, tatag, katapatan, pananagutan, at pananaw. Ganito kami lumalaban para sa mga underdog, sa mga napapabayaan, at sa mga negosyong mas magaling kaysa sa ipinapakita ng kanilang Google ranking.', fr:'Nous ne faisons pas que référencer des sites. Nous nous rebellons — avec détermination, ténacité, honnêteté, responsabilité et vision. C’est ainsi que nous nous battons pour les outsiders, les oubliés et les entreprises qui valent mieux que leur classement Google.', ar:'نحن لا نرفع ترتيب المواقع فحسب. نحن نتمرّد — بهدف وعزيمة وصدق ومسؤولية ورؤية. هكذا نناضل من أجل المستضعَفين والمُهمَلين والشركات الأفضل ممّا يُظهره ترتيبها على Google.' },
    'We don\'t break rules for the thrill of it. We break the ones that were never working for you in the first place. Every decision we make asks one question: does this move the needle, or does it just feel safe?': { es:'No rompemos las reglas por diversión. Rompemos las que nunca funcionaron para ti. Cada decisión que tomamos se hace una pregunta: ¿esto genera resultados o solo da sensación de seguridad?', zh:'我们打破规则，不是为了寻求刺激，而是打破那些从一开始就对你毫无用处的规则。我们做的每个决定都只问一个问题：这能带来实际改变，还是只是图个安心？', vi:'Chúng tôi không phá luật để tìm cảm giác mạnh. Chúng tôi phá những luật vốn chẳng bao giờ có lợi cho bạn. Mỗi quyết định đều hỏi một câu: điều này tạo ra khác biệt, hay chỉ khiến ta thấy an toàn?', tl:'Hindi kami sumisira ng patakaran para sa thrill. Sinisira namin ang mga patakarang hindi naman gumagana para sa iyo mula’t sapul. Bawat desisyon namin ay nagtatanong: may pinagbabago ba ito, o pakiramdam lang na ligtas?', fr:'Nous ne brisons pas les règles pour le frisson. Nous brisons celles qui n’ont jamais marché pour vous. Chaque décision pose une question : est-ce que ça fait avancer les choses, ou est-ce juste rassurant ?', ar:'نحن لا نكسر القواعد من أجل الإثارة. نكسر تلك التي لم تنفعك يومًا من الأساس. كل قرار نتخذه يطرح سؤالًا واحدًا: هل يُحدث هذا فرقًا حقيقيًا، أم أنه مجرّد شعور بالأمان؟' },
    'Rankings don\'t move overnight. Algorithms don\'t care about your timeline. We show up anyway, every week, every report, every client, because the businesses that win online are the ones that refused to quit.': { es:'Las posiciones no cambian de la noche a la mañana. A los algoritmos no les importan tus plazos. Aun así, estamos ahí cada semana, cada informe, cada cliente, porque los negocios que ganan en internet son los que se negaron a rendirse.', zh:'排名不会一夜之间改变。算法不在乎你的时间表。但我们依然全力以赴——每一周、每一份报告、每一位客户，因为在网络上胜出的企业，都是那些拒绝放弃的企业。', vi:'Thứ hạng không thay đổi sau một đêm. Thuật toán không quan tâm đến tiến độ của bạn. Dù vậy chúng tôi vẫn có mặt — mỗi tuần, mỗi báo cáo, mỗi khách hàng — vì những doanh nghiệp chiến thắng trực tuyến là những doanh nghiệp không chịu bỏ cuộc.', tl:'Hindi nagbabago ang ranking magdamag. Walang pakialam ang algorithm sa timeline mo. Nariyan pa rin kami — bawat linggo, bawat ulat, bawat kliyente — dahil ang mga negosyong nananalo online ay ang mga tumangging sumuko.', fr:'Les classements ne bougent pas du jour au lendemain. Les algorithmes se moquent de votre calendrier. Nous sommes là quand même — chaque semaine, chaque rapport, chaque client — parce que les entreprises qui gagnent en ligne sont celles qui ont refusé d’abandonner.', ar:'الترتيب لا يتغيّر بين ليلة وضحاها. الخوارزميات لا تهتمّ بجدولك الزمني. ومع ذلك نحضر — كل أسبوع، كل تقرير، كل عميل — لأن الشركات التي تفوز على الإنترنت هي التي رفضت الاستسلام.' },
    'You hired us to grow your business, not to make ourselves look good. So we tell you the truth, even when it\'s uncomfortable. Especially when it\'s uncomfortable. That\'s the only way real progress gets made.': { es:'Nos contrataste para hacer crecer tu negocio, no para quedar bien. Por eso te decimos la verdad, aunque sea incómoda. Sobre todo cuando es incómoda. Es la única forma de lograr un progreso real.', zh:'你雇我们是为了发展你的业务，不是为了让我们好看。所以我们会对你说实话，哪怕令人不适，尤其是令人不适的时候。因为那才是取得真正进展的唯一途径。', vi:'Bạn thuê chúng tôi để phát triển doanh nghiệp của bạn, không phải để chúng tôi trông đẹp đẽ. Vì vậy chúng tôi nói sự thật, ngay cả khi khó nghe. Nhất là khi khó nghe. Đó là cách duy nhất để có tiến bộ thực sự.', tl:'Kinuha mo kami para palaguin ang negosyo mo, hindi para magmukhang maganda kami. Kaya sinasabi namin ang totoo, kahit hindi kumportable. Lalo na kapag hindi kumportable. Iyon lang ang paraan para magkaroon ng tunay na progreso.', fr:'Vous nous avez engagés pour faire croître votre entreprise, pas pour nous mettre en valeur. Alors nous vous disons la vérité, même quand elle dérange. Surtout quand elle dérange. C’est la seule façon de progresser vraiment.', ar:'لقد وظّفتنا لننمّي نشاطك التجاري، لا لنُحسّن صورتنا. لذا نقول لك الحقيقة، حتى عندما تكون غير مريحة. خصوصًا عندما تكون غير مريحة. فهذه هي الطريقة الوحيدة لتحقيق تقدّم حقيقي.' },
    'We don\'t blame Google. We don\'t point at timelines. When you sign with us, your problem becomes our problem. We own the outcome like it\'s our own business on the line.': { es:'No culpamos a Google. No señalamos los plazos. Cuando firmas con nosotros, tu problema se vuelve nuestro problema. Asumimos el resultado como si fuera nuestro propio negocio el que está en juego.', zh:'我们不会怪罪 Google，也不会拿时间表当借口。当你与我们签约，你的问题就成了我们的问题。我们对结果负责，就像押上的是我们自己的生意。', vi:'Chúng tôi không đổ lỗi cho Google. Chúng tôi không viện cớ tiến độ. Khi bạn ký với chúng tôi, vấn đề của bạn trở thành vấn đề của chúng tôi. Chúng tôi chịu trách nhiệm về kết quả như thể chính doanh nghiệp của mình đang bị đặt cược.', tl:'Hindi namin sinisisi ang Google. Hindi kami nagtuturo sa timeline. Kapag pumirma ka sa amin, ang problema mo ay nagiging problema namin. Pananagutan namin ang resulta na parang sariling negosyo namin ang nakataya.', fr:'Nous ne blâmons pas Google. Nous ne pointons pas les délais. Quand vous signez avec nous, votre problème devient le nôtre. Nous assumons le résultat comme si notre propre entreprise était en jeu.', ar:'نحن لا نلوم Google. ولا نتذرّع بالجداول الزمنية. عندما توقّع معنا، تصبح مشكلتك مشكلتنا. نتحمّل مسؤولية النتيجة وكأنّ نشاطنا التجاري هو المعرّض للخطر.' },
    'We believe every small business deserves a fighting chance online. Not just the ones with big budgets and agencies on retainer. The underdogs. The overlooked. The ones who are better than their Google ranking shows. That\'s exactly who we built this for.': { es:'Creemos que todo pequeño negocio merece una oportunidad real en internet. No solo los que tienen grandes presupuestos y agencias contratadas. Los que parten en desventaja. Los ignorados. Los que valen más de lo que muestra su posición en Google. Para ellos creamos exactamente esto.', zh:'我们相信每一家小企业都应在网络上拥有一搏的机会，而不只是那些预算雄厚、长期聘请代理的公司。那些弱者，那些被忽视者，那些比 Google 排名更优秀的企业——我们打造这一切，正是为了他们。', vi:'Chúng tôi tin mọi doanh nghiệp nhỏ đều xứng đáng có một cơ hội thực sự trên mạng. Không chỉ những nơi ngân sách lớn và có agency túc trực. Những kẻ yếu thế. Những người bị bỏ quên. Những doanh nghiệp giỏi hơn thứ hạng Google của họ. Chính họ là lý do chúng tôi tạo ra điều này.', tl:'Naniniwala kami na bawat maliit na negosyo ay karapat-dapat sa tunay na pagkakataon online. Hindi lang ang mga may malaking budget at naka-retainer na ahensya. Ang mga underdog. Ang mga napapabayaan. Ang mga mas magaling kaysa ipinapakita ng kanilang Google ranking. Para mismo sa kanila namin ginawa ito.', fr:'Nous croyons que chaque petite entreprise mérite une vraie chance en ligne. Pas seulement celles aux gros budgets et aux agences sous contrat. Les outsiders. Les oubliés. Celles qui valent mieux que leur classement Google. C’est exactement pour elles que nous avons créé tout ça.', ar:'نؤمن بأن كل نشاط تجاري صغير يستحق فرصة حقيقية على الإنترنت. ليس فقط أصحاب الميزانيات الكبيرة والوكالات المتعاقدة. المستضعَفون. المُهمَلون. الأفضل ممّا يُظهره ترتيبهم على Google. لأجلهم تحديدًا أنشأنا هذا.' },
    'We exist to Rebel against the agencies that over-promise, the algorithms that favor the big guys, and the belief that small businesses can\'t compete online. We\'re here to prove all three of them wrong.': { es:'Existimos para rebelarnos contra las agencias que prometen de más, los algoritmos que favorecen a los grandes y la creencia de que los pequeños negocios no pueden competir en internet. Estamos aquí para demostrar que los tres se equivocan.', zh:'我们的存在，就是为了反叛那些过度承诺的代理机构、偏袒大公司的算法，以及「小企业无法在网络上竞争」的偏见。我们就是要证明这三者都错了。', vi:'Chúng tôi tồn tại để nổi dậy chống lại những agency hứa hẹn quá lời, những thuật toán thiên vị kẻ lớn, và niềm tin rằng doanh nghiệp nhỏ không thể cạnh tranh trực tuyến. Chúng tôi ở đây để chứng minh cả ba điều đó đều sai.', tl:'Umiiral kami para maghimagsik laban sa mga ahensyang sobra mangako, sa mga algorithm na pumapabor sa malalaki, at sa paniniwalang hindi makakalaban online ang maliliit na negosyo. Nandito kami para patunayang mali ang tatlong iyon.', fr:'Nous existons pour nous rebeller contre les agences qui en promettent trop, les algorithmes qui favorisent les grands, et l’idée que les petites entreprises ne peuvent pas rivaliser en ligne. Nous sommes là pour prouver que ces trois-là ont tort.', ar:'نحن موجودون لنتمرّد على الوكالات التي تُبالغ في الوعود، والخوارزميات التي تحابي الكبار، والاعتقاد بأن الشركات الصغيرة لا تستطيع المنافسة على الإنترنت. نحن هنا لنُثبت خطأ هذه الثلاثة جميعًا.' },

    // ---- sweep: problem descriptions ----
    'A site that looks built in 2010. Visitors bounce before they read a word about what you do.': { es:'Un sitio que parece de 2010. Las visitas se van antes de leer una sola palabra sobre lo que haces.', zh:'一个看起来像 2010 年做的网站。访客还没读到你做什么就已经离开了。', vi:'Một trang web trông như làm từ 2010. Khách rời đi trước khi đọc được một chữ về việc bạn làm.', tl:'Isang site na mukhang gawa noong 2010. Umaalis ang mga bisita bago pa nila mabasa kung ano ang ginagawa mo.', fr:'Un site qui semble dater de 2010. Les visiteurs partent avant même de lire un mot sur ce que vous faites.', ar:'موقع يبدو وكأنه صُمّم عام 2010. يغادر الزوّار قبل أن يقرؤوا كلمة واحدة عمّا تقدّمه.' },
    'Every extra second of load time sends people straight back to the search results, and over to your competitor.': { es:'Cada segundo extra de carga manda a la gente de vuelta a los resultados de búsqueda, y directo a tu competencia.', zh:'每多加载一秒，都会把人直接送回搜索结果，转向你的竞争对手。', vi:'Mỗi giây tải thêm sẽ đẩy người dùng quay lại kết quả tìm kiếm, và sang đối thủ của bạn.', tl:'Bawat dagdag na segundo ng pag-load ay nagpapabalik sa mga tao sa search results, at sa kakumpitensya mo.', fr:'Chaque seconde de chargement en plus renvoie les gens aux résultats de recherche, droit vers votre concurrent.', ar:'كل ثانية تحميل إضافية تُعيد الناس إلى نتائج البحث، ومباشرة إلى منافسك.' },
    'If you don\'t rank, or AI never names you, you\'re losing leads every day to competitors who show up.': { es:'Si no posicionas, o la IA nunca te menciona, pierdes clientes cada día ante competidores que sí aparecen.', zh:'如果你没有排名，或 AI 从不提及你，你每天都在把客户输给那些出现在搜索中的竞争对手。', vi:'Nếu bạn không xếp hạng, hoặc AI không bao giờ nhắc đến bạn, bạn mất khách mỗi ngày vào tay đối thủ xuất hiện.', tl:'Kung hindi ka nagra-rank, o hindi ka binabanggit ng AI, nawawalan ka ng lead araw-araw sa mga kakumpitensyang lumilitaw.', fr:'Si vous n’êtes pas classé, ou si l’IA ne vous nomme jamais, vous perdez des clients chaque jour au profit des concurrents qui apparaissent.', ar:'إن لم تتصدّر، أو لم يذكرك الذكاء الاصطناعي أبدًا، فأنت تخسر عملاء كل يوم لصالح منافسين يظهرون.' },
    'A missing or unmanaged Google Business Profile with few reviews means you\'re left out of the local map when nearby customers search.': { es:'Un Perfil de Google Business inexistente o mal gestionado, con pocas reseñas, te deja fuera del mapa local cuando buscan clientes cercanos.', zh:'缺失或疏于管理、评价寥寥的 Google 商家资料，会让你在附近客户搜索时被排除在本地地图之外。', vi:'Hồ sơ Google Business thiếu hoặc không được quản lý, ít đánh giá, khiến bạn bị loại khỏi bản đồ địa phương khi khách gần đó tìm kiếm.', tl:'Ang nawawala o hindi pinamamahalaang Google Business Profile na may kakaunting review ay nag-iiwan sa iyo sa lokal na mapa kapag naghahanap ang mga kalapit na customer.', fr:'Un profil Google Business absent ou mal géré, avec peu d’avis, vous exclut de la carte locale quand des clients proches cherchent.', ar:'ملف Google Business مفقود أو غير مُدار وبتقييمات قليلة يُقصيك من الخريطة المحلية عندما يبحث العملاء القريبون.' },
    'A clunky mobile site quietly bleeds customers who are searching on their phones.': { es:'Un sitio móvil torpe pierde clientes en silencio mientras buscan desde el teléfono.', zh:'笨拙的移动端网站会在人们用手机搜索时悄悄流失客户。', vi:'Một trang web di động vụng về âm thầm làm mất khách khi họ tìm kiếm trên điện thoại.', tl:'Isang magulong mobile site ang tahimik na nag-uubos ng customer habang naghahanap sila sa kanilang telepono.', fr:'Un site mobile maladroit perd discrètement des clients qui cherchent depuis leur téléphone.', ar:'موقع جوال رديء يفقدك العملاء بهدوء وهم يبحثون من هواتفهم.' },
    'Wix, Squarespace, GoDaddy… weekends wrestling templates, and it still looks generic.': { es:'Wix, Squarespace, GoDaddy… fines de semana peleando con plantillas, y aun así se ve genérico.', zh:'Wix、Squarespace、GoDaddy……周末与模板较劲，结果还是千篇一律。', vi:'Wix, Squarespace, GoDaddy… cuối tuần vật lộn với mẫu có sẵn, mà vẫn trông chung chung.', tl:'Wix, Squarespace, GoDaddy… weekend na pakikipagbuno sa template, at mukhang generic pa rin.', fr:'Wix, Squarespace, GoDaddy… des week-ends à se battre avec des modèles, et ça reste générique.', ar:'Wix وSquarespace وGoDaddy… عطلات نهاية الأسبوع في صراع مع القوالب، ويبقى المظهر عاديًا.' },

    // ---- sweep: problem stats ----
    '75% judge a business\'s credibility by its website': { es:'<b>75%</b> juzga la credibilidad de un negocio por su sitio web', zh:'<b>75%</b> 的人根据网站判断一家企业是否可信', vi:'<b>75%</b> đánh giá độ tin cậy của doanh nghiệp qua trang web', tl:'<b>75%</b> ang humahatol sa kredibilidad ng negosyo base sa website nito', fr:'<b>75 %</b> jugent la crédibilité d’une entreprise selon son site', ar:'<b>75%</b> يحكمون على مصداقية النشاط من خلال موقعه' },
    '53% leave a page that takes over 3 seconds to load': { es:'<b>53%</b> abandona una página que tarda más de 3 segundos en cargar', zh:'<b>53%</b> 会离开加载超过 3 秒的页面', vi:'<b>53%</b> rời khỏi trang mất hơn 3 giây để tải', tl:'<b>53%</b> ang umaalis sa page na mahigit 3 segundo mag-load', fr:'<b>53 %</b> quittent une page qui met plus de 3 secondes à charger', ar:'<b>53%</b> يغادرون صفحة يستغرق تحميلها أكثر من 3 ثوانٍ' },
    '46% of all Google searches are looking for local businesses': { es:'<b>46%</b> de todas las búsquedas en Google buscan negocios locales', zh:'<b>46%</b> 的 Google 搜索都在寻找本地企业', vi:'<b>46%</b> trong tất cả tìm kiếm Google đang tìm doanh nghiệp địa phương', tl:'<b>46%</b> ng lahat ng paghahanap sa Google ay naghahanap ng lokal na negosyo', fr:'<b>46 %</b> de toutes les recherches Google visent des entreprises locales', ar:'<b>46%</b> من كل عمليات بحث Google تبحث عن شركات محلية' },
    '2× more likely to be considered reputable with a complete profile': { es:'<b>2×</b> más probabilidades de parecer confiable con un perfil completo', zh:'拥有完整资料，被认为可信的可能性高 <b>2×</b>', vi:'Khả năng được xem là uy tín cao gấp <b>2×</b> khi có hồ sơ đầy đủ', tl:'<b>2×</b> mas malamang ituring na kapani-paniwala kapag kumpleto ang profile', fr:'<b>2×</b> plus de chances d’être jugé fiable avec un profil complet', ar:'احتمال أكبر بـ <b>2×</b> لاعتبارك موثوقًا بملف مكتمل' },
    '60%+ of Google searches happen on a mobile device': { es:'<b>60%+</b> de las búsquedas en Google ocurren en un móvil', zh:'<b>60%+</b> 的 Google 搜索发生在移动设备上', vi:'<b>60%+</b> tìm kiếm Google diễn ra trên thiết bị di động', tl:'<b>60%+</b> ng paghahanap sa Google ay sa mobile device nangyayari', fr:'<b>60 %+</b> des recherches Google se font sur mobile', ar:'<b>60%+</b> من عمليات بحث Google تتم على هاتف محمول' },
    '50ms is all it takes for visitors to form an opinion of your site': { es:'<b>50ms</b> es todo lo que necesita un visitante para formarse una opinión de tu sitio', zh:'访客只需 <b>50ms</b> 就会对你的网站形成印象', vi:'Chỉ <b>50ms</b> là đủ để khách hình thành ấn tượng về trang của bạn', tl:'<b>50ms</b> lang ang kailangan para magkaroon ng opinyon ang bisita sa site mo', fr:'<b>50 ms</b> suffisent à un visiteur pour se faire une opinion de votre site', ar:'<b>50 ميلي ثانية</b> تكفي ليكوّن الزائر رأيًا عن موقعك' },

    // ---- sweep: process eyebrow + step labels ----
    'The process': { es:'El proceso', zh:'流程', vi:'Quy trình', tl:'Ang Proseso', fr:'Le processus', ar:'العملية' },
    'STEP 01': { es:'PASO 01', zh:'步骤 01', vi:'BƯỚC 01', tl:'HAKBANG 01', fr:'ÉTAPE 01', ar:'الخطوة 01' },
    'STEP 02': { es:'PASO 02', zh:'步骤 02', vi:'BƯỚC 02', tl:'HAKBANG 02', fr:'ÉTAPE 02', ar:'الخطوة 02' },
    'STEP 03': { es:'PASO 03', zh:'步骤 03', vi:'BƯỚC 03', tl:'HAKBANG 03', fr:'ÉTAPE 03', ar:'الخطوة 03' },
    'STEP 04': { es:'PASO 04', zh:'步骤 04', vi:'BƯỚC 04', tl:'HAKBANG 04', fr:'ÉTAPE 04', ar:'الخطوة 04' },

    // ---- sweep: promise ----
    '✓ Free audit': { es:'✓ Auditoría <b>gratis</b>', zh:'✓ <b>免费</b>诊断', vi:'✓ Đánh giá <b>miễn phí</b>', tl:'✓ <b>Libreng</b> audit', fr:'✓ Audit <b>gratuit</b>', ar:'✓ تدقيق <b>مجاني</b>' },
    '✓ No surprise fees': { es:'✓ <b>Sin</b> cargos sorpresa', zh:'✓ <b>无</b>意外费用', vi:'✓ <b>Không</b> phí bất ngờ', tl:'✓ <b>Walang</b> sorpresang bayarin', fr:'✓ <b>Aucun</b> frais caché', ar:'✓ <b>بلا</b> رسوم مفاجئة' },
    '✓ Dedicated team': { es:'✓ Equipo <b>dedicado</b>', zh:'✓ <b>专属</b>团队', vi:'✓ Đội ngũ <b>tận tâm</b>', tl:'✓ <b>Dedikadong</b> team', fr:'✓ Équipe <b>dédiée</b>', ar:'✓ فريق <b>مخصّص</b>' },
    '✓ Built for Google & AI': { es:'✓ <b>Hecho para</b> Google e IA', zh:'✓ <b>专为</b> Google 和 AI 打造', vi:'✓ <b>Dành cho</b> Google & AI', tl:'✓ <b>Ginawa para sa</b> Google at AI', fr:'✓ <b>Conçu pour</b> Google et l’IA', ar:'✓ <b>مصمّم لـ</b> Google والذكاء الاصطناعي' },

    // ---- sweep: testimonials ----
    '"Rank Rebels built us a clean, professional site and got our Google profile dialed in. We\'re finally getting calls and booking jobs straight from search, and they were easy to work with start to finish."': { es:'«Rank Rebels nos creó un sitio limpio y profesional y dejó nuestro perfil de Google perfecto. Por fin recibimos llamadas y agendamos trabajos directo desde las búsquedas, y fue fácil trabajar con ellos de principio a fin.»', zh:'“Rank Rebels 为我们打造了简洁专业的网站，并把我们的 Google 资料调校得很到位。我们终于能直接从搜索中接到来电和预约，而且从头到尾合作都很轻松。”', vi:'“Rank Rebels đã xây cho chúng tôi một trang web gọn gàng, chuyên nghiệp và chỉnh chu hồ sơ Google. Cuối cùng chúng tôi nhận được cuộc gọi và đặt lịch ngay từ tìm kiếm, và làm việc với họ rất dễ chịu từ đầu đến cuối.”', tl:'“Gumawa sa amin ang Rank Rebels ng malinis, propesyonal na site at inayos ang aming Google profile. Sa wakas ay tumatanggap na kami ng tawag at booking diretso mula sa search, at madaling katrabaho sila mula simula hanggang dulo.”', fr:'« Rank Rebels nous a créé un site soigné et professionnel et a parfaitement réglé notre profil Google. Nous recevons enfin des appels et des réservations directement depuis la recherche, et ils ont été faciles à suivre du début à la fin. »', ar:'”أنشأت لنا Rank Rebels موقعًا أنيقًا واحترافيًا وضبطت ملفنا على Google تمامًا. أخيرًا صرنا نتلقّى المكالمات ونحجز الأعمال مباشرة من البحث، وكان التعامل معهم سهلًا من البداية إلى النهاية.“' },
    '"Our new website actually represents who we are now. The team handled everything (design, copy, the works) and we finally look like the firm we are."': { es:'«Nuestro nuevo sitio por fin representa quiénes somos ahora. El equipo se encargó de todo (diseño, textos, lo que sea) y por fin lucimos como la empresa que somos.»', zh:'“我们的新网站终于代表了如今的我们。团队搞定了一切（设计、文案、方方面面），我们终于看起来像我们应有的公司。”', vi:'“Trang web mới của chúng tôi cuối cùng đã thể hiện đúng con người hiện tại của chúng tôi. Đội ngũ lo hết mọi thứ (thiết kế, nội dung, tất cả) và cuối cùng chúng tôi trông đúng tầm công ty của mình.”', tl:'“Sa wakas ay kinakatawan na ng bago naming website kung sino kami ngayon. Inasikaso ng team ang lahat (disenyo, copy, lahat-lahat) at sa wakas ay mukha na kaming kompanyang dapat namin.”', fr:'« Notre nouveau site reflète enfin qui nous sommes aujourd’hui. L’équipe s’est occupée de tout (design, textes, tout) et nous avons enfin l’image de l’entreprise que nous sommes. »', ar:'”موقعنا الجديد يعبّر أخيرًا عن هويتنا الحالية. تولّى الفريق كل شيء (التصميم والمحتوى وكل التفاصيل) وأصبحنا أخيرًا نبدو بمستوى شركتنا الحقيقي.“' },

    // ---- sweep: footer + cookie ----
    'Privacy': { es:'Privacidad', zh:'隐私', vi:'Quyền riêng tư', tl:'Privacy', fr:'Confidentialité', ar:'الخصوصية' },
    'Team login →': { es:'Acceso del equipo →', zh:'团队登录 →', vi:'Đăng nhập nhóm →', tl:'Team login →', fr:'Connexion équipe →', ar:'دخول الفريق →' },
    'We use cookies for analytics to improve our site. See our Privacy Policy.': { es:'Usamos cookies de análisis para mejorar nuestro sitio. Consulta nuestra <a href="/privacy" style="color:var(--brand);font-weight:600">Política de Privacidad</a>.', zh:'我们使用分析 Cookie 来改进网站。请查看我们的<a href="/privacy" style="color:var(--brand);font-weight:600">隐私政策</a>。', vi:'Chúng tôi dùng cookie phân tích để cải thiện trang web. Xem <a href="/privacy" style="color:var(--brand);font-weight:600">Chính sách Quyền riêng tư</a> của chúng tôi.', tl:'Gumagamit kami ng cookies para sa analytics para mapabuti ang aming site. Tingnan ang aming <a href="/privacy" style="color:var(--brand);font-weight:600">Patakaran sa Privacy</a>.', fr:'Nous utilisons des cookies d’analyse pour améliorer notre site. Consultez notre <a href="/privacy" style="color:var(--brand);font-weight:600">politique de confidentialité</a>.', ar:'نستخدم ملفات تعريف الارتباط للتحليلات لتحسين موقعنا. اطّلِع على <a href="/privacy" style="color:var(--brand);font-weight:600">سياسة الخصوصية</a>.' },

    // ---- packages ----
    'Packages': { es:'Paquetes', zh:'套餐', vi:'Gói dịch vụ', tl:'Mga Package', fr:'Forfaits', ar:'الباقات' },
    'Pick your plan and get started today': { es:'Elige tu plan y <span class="hl">empieza hoy</span>', zh:'选择你的方案，<span class="hl">今天就开始</span>', vi:'Chọn gói của bạn và <span class="hl">bắt đầu ngay hôm nay</span>', tl:'Piliin ang plano mo at <span class="hl">magsimula ngayon</span>', fr:'Choisissez votre forfait et <span class="hl">lancez-vous aujourd’hui</span>', ar:'اختر خطتك <span class="hl">وابدأ اليوم</span>' },
    'A one-time build to launch your custom site, plus a simple monthly plan that keeps you found, fresh, and growing. Start online in minutes.': { es:'Un pago único para lanzar tu sitio a medida, más un plan mensual sencillo que te mantiene visible, actualizado y creciendo. Empieza en línea en minutos.', zh:'一次性建站费用让你的定制网站上线，再加上简单的按月方案，让你持续被发现、保持新鲜并不断成长。几分钟内在线开始。', vi:'Một khoản xây dựng một lần để ra mắt trang web riêng của bạn, cộng với gói hằng tháng đơn giản giúp bạn được tìm thấy, luôn mới và phát triển. Bắt đầu trực tuyến trong vài phút.', tl:'Isang beses na bayad sa build para i-launch ang custom mong site, kasama ang simpleng buwanang plano na nagpapanatili sa iyong matagpuan, sariwa, at lumalago. Magsimula online sa loob ng ilang minuto.', fr:'Un build unique pour lancer votre site sur mesure, plus un forfait mensuel simple qui vous garde visible, à jour et en croissance. Lancez-vous en ligne en quelques minutes.', ar:'بناء لمرة واحدة لإطلاق موقعك المخصّص، بالإضافة إلى خطة شهرية بسيطة تبقيك مرئيًا ومتجددًا ونامِيًا. ابدأ عبر الإنترنت خلال دقائق.' },
    // tier names
    'Starter': { es:'Inicial', zh:'入门版', vi:'Khởi đầu', tl:'Starter', fr:'Essentiel', ar:'المبتدئ' },
    'Growth': { es:'Crecimiento', zh:'成长版', vi:'Tăng trưởng', tl:'Growth', fr:'Croissance', ar:'النمو' },
    'Pro': { es:'Pro', zh:'专业版', vi:'Pro', tl:'Pro', fr:'Pro', ar:'الاحترافي' },
    'Most popular': { es:'Más popular', zh:'最受欢迎', vi:'Phổ biến nhất', tl:'Pinakasikat', fr:'Le plus choisi', ar:'الأكثر شيوعًا' },
    // tier taglines
    'Get a professional site live and start showing up on Google.': { es:'Pon en marcha un sitio profesional y empieza a aparecer en Google.', zh:'让专业网站上线，开始出现在 Google 上。', vi:'Đưa một trang web chuyên nghiệp lên mạng và bắt đầu xuất hiện trên Google.', tl:'Mag-live ng propesyonal na site at magsimulang lumitaw sa Google.', fr:'Mettez en ligne un site professionnel et commencez à apparaître sur Google.', ar:'أطلِق موقعًا احترافيًا وابدأ بالظهور على Google.' },
    'Get found, get reviews, and turn searches into booked customers.': { es:'Hazte visible, consigue reseñas y convierte las búsquedas en clientes agendados.', zh:'被发现、获得评价，把搜索变成预约客户。', vi:'Được tìm thấy, nhận đánh giá và biến lượt tìm kiếm thành khách đã đặt.', tl:'Matagpuan, magkaroon ng review, at gawing booking ang mga paghahanap.', fr:'Soyez trouvé, obtenez des avis et transformez les recherches en clients réservés.', ar:'كن مرئيًا، واحصل على التقييمات، وحوِّل عمليات البحث إلى عملاء محجوزين.' },
    'Dominate your market with the full system and a dedicated strategist.': { es:'Domina tu mercado con el sistema completo y un estratega dedicado.', zh:'用完整系统和专属策略师称霸你的市场。', vi:'Thống lĩnh thị trường của bạn với hệ thống đầy đủ và một chuyên gia chiến lược riêng.', tl:'Manaig sa iyong merkado gamit ang buong sistema at isang dedikadong strategist.', fr:'Dominez votre marché avec le système complet et un stratège dédié.', ar:'تصدّر سوقك بالنظام الكامل وخبير استراتيجي مخصّص.' },
    // prices (number kept, label translated)
    '$1,500 build': { es:'$1,500 <small>inicial</small>', zh:'$1,500 <small>建站</small>', vi:'$1,500 <small>xây dựng</small>', tl:'$1,500 <small>build</small>', fr:'$1,500 <small>build</small>', ar:'$1,500 <small>بناء</small>' },
    '$2,500 build': { es:'$2,500 <small>inicial</small>', zh:'$2,500 <small>建站</small>', vi:'$2,500 <small>xây dựng</small>', tl:'$2,500 <small>build</small>', fr:'$2,500 <small>build</small>', ar:'$2,500 <small>بناء</small>' },
    '$4,500 build': { es:'$4,500 <small>inicial</small>', zh:'$4,500 <small>建站</small>', vi:'$4,500 <small>xây dựng</small>', tl:'$4,500 <small>build</small>', fr:'$4,500 <small>build</small>', ar:'$4,500 <small>بناء</small>' },
    'then $99 / month': { es:'luego <b>$99</b> / mes', zh:'然后 <b>$99</b> / 月', vi:'sau đó <b>$99</b> / tháng', tl:'tapos <b>$99</b> / buwan', fr:'puis <b>$99</b> / mois', ar:'ثم <b>$99</b> / شهر' },
    'then $299 / month': { es:'luego <b>$299</b> / mes', zh:'然后 <b>$299</b> / 月', vi:'sau đó <b>$299</b> / tháng', tl:'tapos <b>$299</b> / buwan', fr:'puis <b>$299</b> / mois', ar:'ثم <b>$299</b> / شهر' },
    'then $599 / month': { es:'luego <b>$599</b> / mes', zh:'然后 <b>$599</b> / 月', vi:'sau đó <b>$599</b> / tháng', tl:'tapos <b>$599</b> / buwan', fr:'puis <b>$599</b> / mois', ar:'ثم <b>$599</b> / شهر' },
    // feature bullets
    'Custom 5-page website': { es:'Sitio web a medida de 5 páginas', zh:'定制 5 页网站', vi:'Trang web tùy chỉnh 5 trang', tl:'Custom na 5-page na website', fr:'Site sur mesure de 5 pages', ar:'موقع مخصّص من 5 صفحات' },
    'Mobile-first, fast & SEO-ready': { es:'Optimizado para móvil, rápido y listo para SEO', zh:'移动优先、快速、SEO 就绪', vi:'Ưu tiên di động, nhanh & sẵn sàng SEO', tl:'Mobile-first, mabilis at SEO-ready', fr:'Mobile d’abord, rapide et prêt pour le SEO', ar:'الجوال أولاً، سريع وجاهز لـ SEO' },
    'Google Business Profile setup': { es:'Configuración del Perfil de Google Business', zh:'Google 商家资料设置', vi:'Thiết lập Hồ sơ Google Business', tl:'Pag-set up ng Google Business Profile', fr:'Configuration du profil Google Business', ar:'إعداد الملف التجاري على Google' },
    'Lead capture & contact forms': { es:'Captación de clientes y formularios de contacto', zh:'潜在客户捕获与联系表单', vi:'Thu thập khách hàng tiềm năng & biểu mẫu liên hệ', tl:'Lead capture at contact forms', fr:'Captation de prospects et formulaires de contact', ar:'التقاط العملاء ونماذج التواصل' },
    'Hosting, security & maintenance': { es:'Alojamiento, seguridad y mantenimiento', zh:'托管、安全与维护', vi:'Lưu trữ, bảo mật & bảo trì', tl:'Hosting, security at maintenance', fr:'Hébergement, sécurité et maintenance', ar:'الاستضافة والأمان والصيانة' },
    'Email support': { es:'Soporte por correo', zh:'电子邮件支持', vi:'Hỗ trợ qua email', tl:'Suportang email', fr:'Assistance par e-mail', ar:'دعم عبر البريد الإلكتروني' },
    'Everything in Starter, plus': { es:'Todo lo del plan Inicial, más', zh:'包含入门版的全部，另加', vi:'Mọi thứ trong gói Khởi đầu, cộng thêm', tl:'Lahat sa Starter, plus', fr:'Tout l’Essentiel, plus', ar:'كل ما في باقة المبتدئ، بالإضافة إلى' },
    'Up to 10 custom pages': { es:'Hasta 10 páginas a medida', zh:'最多 10 个定制页面', vi:'Tối đa 10 trang tùy chỉnh', tl:'Hanggang 10 custom na page', fr:'Jusqu’à 10 pages sur mesure', ar:'حتى 10 صفحات مخصّصة' },
    'Ongoing SEO for Google & AI search': { es:'SEO continuo para Google y búsqueda con IA', zh:'针对 Google 和 AI 搜索的持续 SEO', vi:'SEO liên tục cho Google & tìm kiếm AI', tl:'Tuloy-tuloy na SEO para sa Google at AI search', fr:'SEO continu pour Google et la recherche IA', ar:'SEO مستمر لـ Google وبحث الذكاء الاصطناعي' },
    'Google Business Profile management': { es:'Gestión del Perfil de Google Business', zh:'Google 商家资料管理', vi:'Quản lý Hồ sơ Google Business', tl:'Pamamahala ng Google Business Profile', fr:'Gestion du profil Google Business', ar:'إدارة الملف التجاري على Google' },
    '1 blog post every month': { es:'1 publicación de blog cada mes', zh:'每月 1 篇博客文章', vi:'1 bài blog mỗi tháng', tl:'1 blog post kada buwan', fr:'1 article de blog par mois', ar:'مقال مدوّنة واحد كل شهر' },
    'Review generation': { es:'Generación de reseñas', zh:'评价生成', vi:'Tạo đánh giá', tl:'Review generation', fr:'Génération d’avis', ar:'توليد التقييمات' },
    'Monthly performance report': { es:'Informe de rendimiento mensual', zh:'每月绩效报告', vi:'Báo cáo hiệu suất hằng tháng', tl:'Buwanang performance report', fr:'Rapport de performance mensuel', ar:'تقرير أداء شهري' },
    'Bumper-to-bumper warranty': { es:'Garantía total', zh:'全方位保障', vi:'Bảo hành toàn diện', tl:'Bumper-to-bumper na warranty', fr:'Garantie tout compris', ar:'ضمان شامل' },
    'Everything in Growth, plus': { es:'Todo lo del plan Crecimiento, más', zh:'包含成长版的全部，另加', vi:'Mọi thứ trong gói Tăng trưởng, cộng thêm', tl:'Lahat sa Growth, plus', fr:'Tout Croissance, plus', ar:'كل ما في باقة النمو، بالإضافة إلى' },
    'E-commerce or online booking': { es:'Comercio electrónico o reservas en línea', zh:'电商或在线预订', vi:'Thương mại điện tử hoặc đặt lịch trực tuyến', tl:'E-commerce o online booking', fr:'E-commerce ou réservation en ligne', ar:'متجر إلكتروني أو حجز عبر الإنترنت' },
    'Advanced local SEO + landing pages': { es:'SEO local avanzado + páginas de aterrizaje', zh:'高级本地 SEO + 落地页', vi:'SEO địa phương nâng cao + trang đích', tl:'Advanced na local SEO + landing pages', fr:'SEO local avancé + pages d’atterrissage', ar:'SEO محلي متقدّم + صفحات هبوط' },
    'Social media posting': { es:'Publicaciones en redes sociales', zh:'社交媒体发布', vi:'Đăng bài mạng xã hội', tl:'Social media posting', fr:'Publication sur les réseaux sociaux', ar:'النشر على وسائل التواصل' },
    'Conversion optimization': { es:'Optimización de conversiones', zh:'转化优化', vi:'Tối ưu chuyển đổi', tl:'Conversion optimization', fr:'Optimisation des conversions', ar:'تحسين التحويلات' },
    'Priority support + dedicated strategist': { es:'Soporte prioritario + estratega dedicado', zh:'优先支持 + 专属策略师', vi:'Hỗ trợ ưu tiên + chuyên gia chiến lược riêng', tl:'Priority support + dedikadong strategist', fr:'Support prioritaire + stratège dédié', ar:'دعم بأولوية + خبير استراتيجي مخصّص' },
    'Quarterly strategy calls': { es:'Llamadas estratégicas trimestrales', zh:'每季度策略通话', vi:'Cuộc gọi chiến lược hằng quý', tl:'Quarterly na strategy calls', fr:'Appels stratégiques trimestriels', ar:'مكالمات استراتيجية ربع سنوية' },
    // tier buttons
    'Start Starter →': { es:'Empezar Inicial →', zh:'开始入门版 →', vi:'Bắt đầu Khởi đầu →', tl:'Simulan ang Starter →', fr:'Choisir Essentiel →', ar:'ابدأ المبتدئ →' },
    'Start Growth →': { es:'Empezar Crecimiento →', zh:'开始成长版 →', vi:'Bắt đầu Tăng trưởng →', tl:'Simulan ang Growth →', fr:'Choisir Croissance →', ar:'ابدأ النمو →' },
    'Start Pro →': { es:'Empezar Pro →', zh:'开始专业版 →', vi:'Bắt đầu Pro →', tl:'Simulan ang Pro →', fr:'Choisir Pro →', ar:'ابدأ الاحترافي →' },
    'Month-to-month, or save with a 1- or 2-year plan. No surprise lock-in — you always own your site.': { es:'Mes a mes, o ahorra con un plan de 1 o 2 años. Sin ataduras sorpresa: tu sitio siempre es tuyo.', zh:'可按月，也可选择 1 年或 2 年方案省更多。没有意外锁定——网站始终归你所有。', vi:'Theo từng tháng, hoặc tiết kiệm với gói 1 hoặc 2 năm. Không ràng buộc bất ngờ — trang web luôn là của bạn.', tl:'Month-to-month, o mag-ipon sa 1- o 2-taong plano. Walang sorpresang lock-in — sa iyo lagi ang site mo.', fr:'Au mois, ou économisez avec un forfait 1 ou 2 ans. Aucun engagement caché — votre site vous appartient toujours.', ar:'شهريًا، أو وفّر مع خطة سنة أو سنتين. لا التزام مفاجئ — موقعك ملكك دائمًا.' },
    // add-ons
    'À la carte add-ons': { es:'Complementos a la carta', zh:'单点附加服务', vi:'Tiện ích bổ sung tùy chọn', tl:'À la carte na add-ons', fr:'Options à la carte', ar:'إضافات حسب الطلب' },
    'Bolt these onto any package — or grab them on their own. Everything you need to look established and grow.': { es:'Añádelos a cualquier paquete, o tómalos por separado. Todo lo que necesitas para verte establecido y crecer.', zh:'可附加到任何套餐，也可单独购买。让你显得专业并不断成长所需的一切。', vi:'Gắn vào bất kỳ gói nào — hoặc mua riêng. Mọi thứ bạn cần để trông chuyên nghiệp và phát triển.', tl:'Idagdag sa kahit anong package — o kunin nang mag-isa. Lahat ng kailangan mo para mukhang establisado at lumago.', fr:'Ajoutez-les à n’importe quel forfait — ou prenez-les seuls. Tout pour paraître établi et grandir.', ar:'أضِفها إلى أي باقة — أو احصل عليها وحدها. كل ما تحتاجه لتبدو راسخًا وتنمو.' },
    'Logo & brand identity': { es:'Logo e identidad de marca', zh:'标志与品牌形象', vi:'Logo & nhận diện thương hiệu', tl:'Logo at brand identity', fr:'Logo et identité de marque', ar:'الشعار وهوية العلامة' },
    'Custom logo, color system, and brand artwork that makes you look established on day one.': { es:'Logo a medida, sistema de color y arte de marca que te hace ver establecido desde el primer día.', zh:'定制标志、配色系统和品牌视觉，让你从第一天起就显得专业可靠。', vi:'Logo tùy chỉnh, hệ màu và hình ảnh thương hiệu giúp bạn trông chuyên nghiệp ngay từ ngày đầu.', tl:'Custom na logo, color system, at brand artwork na nagpapaestablisado sa iyo mula day one.', fr:'Logo sur mesure, système de couleurs et visuels de marque qui vous donnent une image établie dès le premier jour.', ar:'شعار مخصّص ونظام ألوان وهوية بصرية تجعلك تبدو راسخًا من اليوم الأول.' },
    'Social media launch kit': { es:'Kit de lanzamiento en redes sociales', zh:'社交媒体启动套件', vi:'Bộ khởi động mạng xã hội', tl:'Social media launch kit', fr:'Kit de lancement réseaux sociaux', ar:'حزمة إطلاق وسائل التواصل' },
    'Profiles set up, branded templates, and a 30-day content calendar to hit the ground running.': { es:'Perfiles configurados, plantillas con tu marca y un calendario de contenido de 30 días para arrancar con todo.', zh:'设置好资料、品牌模板，以及 30 天内容日历，让你迅速起步。', vi:'Thiết lập hồ sơ, mẫu thương hiệu và lịch nội dung 30 ngày để bắt đầu ngay.', tl:'Naka-set up na profiles, branded templates, at 30-araw na content calendar para makaumpisa agad.', fr:'Profils configurés, modèles à votre marque et calendrier de contenu de 30 jours pour démarrer fort.', ar:'إعداد الحسابات وقوالب موسومة وتقويم محتوى لـ 30 يومًا لتنطلق بسرعة.' },
    'E-commerce & booking': { es:'Comercio electrónico y reservas', zh:'电商与预订', vi:'Thương mại điện tử & đặt lịch', tl:'E-commerce at booking', fr:'E-commerce et réservation', ar:'المتجر والحجز' },
    'Sell products or take bookings and deposits online with secure checkout built in.': { es:'Vende productos o recibe reservas y depósitos en línea con pago seguro integrado.', zh:'通过内置安全结账在线销售产品或接受预订与定金。', vi:'Bán sản phẩm hoặc nhận đặt lịch và đặt cọc trực tuyến với thanh toán an toàn tích hợp.', tl:'Magbenta ng produkto o tumanggap ng booking at deposito online na may secure checkout.', fr:'Vendez des produits ou prenez des réservations et acomptes en ligne avec paiement sécurisé intégré.', ar:'بِع المنتجات أو استقبِل الحجوزات والعرابين عبر الإنترنت مع دفع آمن مدمج.' },
    'SEO & AI search': { es:'SEO y búsqueda con IA', zh:'SEO 与 AI 搜索', vi:'SEO & tìm kiếm AI', tl:'SEO at AI search', fr:'SEO et recherche IA', ar:'SEO وبحث الذكاء الاصطناعي' },
    'Ongoing optimization to climb Google and surface when customers ask AI for a recommendation.': { es:'Optimización continua para escalar en Google y aparecer cuando los clientes le piden recomendaciones a la IA.', zh:'持续优化以提升 Google 排名，并在客户向 AI 寻求推荐时出现。', vi:'Tối ưu liên tục để leo hạng Google và xuất hiện khi khách hàng hỏi AI để được giới thiệu.', tl:'Tuloy-tuloy na optimization para umakyat sa Google at lumitaw kapag humihingi ng rekomendasyon ang customer sa AI.', fr:'Optimisation continue pour grimper sur Google et apparaître quand les clients demandent une recommandation à l’IA.', ar:'تحسين مستمر للصعود في Google والظهور عندما يطلب العملاء توصية من الذكاء الاصطناعي.' },
    'Google Business management': { es:'Gestión de Google Business', zh:'Google 商家管理', vi:'Quản lý Google Business', tl:'Pamamahala ng Google Business', fr:'Gestion Google Business', ar:'إدارة Google Business' },
    'We manage your listing to win the local Map pack and drive calls, directions, and reviews.': { es:'Gestionamos tu ficha para ganar el paquete de mapas local y generar llamadas, indicaciones y reseñas.', zh:'我们管理你的商家信息，赢得本地地图栏，并带来来电、导航和评价。', vi:'Chúng tôi quản lý hồ sơ của bạn để chiến thắng Map pack địa phương và tạo cuộc gọi, chỉ đường và đánh giá.', tl:'Pinamamahalaan namin ang listing mo para manalo sa lokal na Map pack at magdulot ng tawag, direksyon, at review.', fr:'Nous gérons votre fiche pour gagner le pack local et générer appels, itinéraires et avis.', ar:'نُدير بطاقتك للفوز بحزمة الخرائط المحلية وجلب المكالمات والاتجاهات والتقييمات.' },
    'Automated review requests that build the 5-star reputation customers check before they call.': { es:'Solicitudes de reseñas automáticas que construyen la reputación de 5 estrellas que los clientes revisan antes de llamar.', zh:'自动评价邀请，打造客户致电前都会查看的五星口碑。', vi:'Yêu cầu đánh giá tự động xây dựng danh tiếng 5 sao mà khách hàng kiểm tra trước khi gọi.', tl:'Awtomatikong review requests na bumubuo ng 5-star na reputasyong tinitingnan ng customer bago tumawag.', fr:'Demandes d’avis automatisées qui bâtissent la réputation 5 étoiles que les clients vérifient avant d’appeler.', ar:'طلبات تقييم تلقائية تبني سمعة 5 نجوم يتحقّق منها العملاء قبل الاتصال.' },
    'one-time': { es:'pago único', zh:'一次性', vi:'một lần', tl:'one-time', fr:'unique', ar:'مرة واحدة' },
    'Add →': { es:'Añadir →', zh:'添加 →', vi:'Thêm →', tl:'Idagdag →', fr:'Ajouter →', ar:'أضِف →' },
    '$750 one-time': { es:'$750 <small>pago único</small>', zh:'$750 <small>一次性</small>', vi:'$750 <small>một lần</small>', tl:'$750 <small>one-time</small>', fr:'$750 <small>unique</small>', ar:'$750 <small>مرة واحدة</small>' },
    '$600 one-time': { es:'$600 <small>pago único</small>', zh:'$600 <small>一次性</small>', vi:'$600 <small>một lần</small>', tl:'$600 <small>one-time</small>', fr:'$600 <small>unique</small>', ar:'$600 <small>مرة واحدة</small>' },
    '$270 / month': { es:'$270 <small>/ mes</small>', zh:'$270 <small>/ 月</small>', vi:'$270 <small>/ tháng</small>', tl:'$270 <small>/ buwan</small>', fr:'$270 <small>/ mois</small>', ar:'$270 <small>/ شهر</small>' },
    '$149 / month': { es:'$149 <small>/ mes</small>', zh:'$149 <small>/ 月</small>', vi:'$149 <small>/ tháng</small>', tl:'$149 <small>/ buwan</small>', fr:'$149 <small>/ mois</small>', ar:'$149 <small>/ شهر</small>' },
    '$99 / month': { es:'$99 <small>/ mes</small>', zh:'$99 <small>/ 月</small>', vi:'$99 <small>/ tháng</small>', tl:'$99 <small>/ buwan</small>', fr:'$99 <small>/ mois</small>', ar:'$99 <small>/ شهر</small>' },

    // ---- start your project ----
    'Get started': { es:'Empieza', zh:'开始', vi:'Bắt đầu', tl:'Magsimula', fr:'Commencer', ar:'ابدأ' },
    'Ready to claim your spot?': { es:'¿Listo para <span class="hl">reservar tu lugar</span>?', zh:'准备好<span class="hl">占据你的位置</span>了吗？', vi:'Sẵn sàng <span class="hl">giữ chỗ của bạn</span>?', tl:'Handa nang <span class="hl">angkinin ang lugar mo</span>?', fr:'Prêt à <span class="hl">réserver votre place</span> ?', ar:'مستعدّ <span class="hl">لحجز مكانك</span>؟' },
    'Two easy ways to kick off — whichever fits you.': { es:'Dos formas fáciles de empezar, la que mejor te quede.', zh:'两种简单的开始方式，任你选择。', vi:'Hai cách dễ dàng để bắt đầu — tùy bạn chọn.', tl:'Dalawang madaling paraan para magsimula — kung alin man ang bagay sa iyo.', fr:'Deux façons simples de démarrer — au choix.', ar:'طريقتان سهلتان للبدء — اختر ما يناسبك.' },
    'Book a free strategy call': { es:'Reserva una llamada estratégica gratis', zh:'预约免费策略通话', vi:'Đặt lịch gọi tư vấn chiến lược miễn phí', tl:'Mag-book ng libreng strategy call', fr:'Réservez un appel stratégique gratuit', ar:'احجز مكالمة استراتيجية مجانية' },
    'Grab a time and we\'ll map out your site, your search presence, and a plan to get you more customers — no pressure.': { es:'Elige un horario y trazaremos tu sitio, tu presencia en buscadores y un plan para conseguirte más clientes, sin compromiso.', zh:'选个时间，我们将为你规划网站、搜索表现，以及一个为你带来更多客户的方案——毫无压力。', vi:'Chọn một thời gian và chúng tôi sẽ phác thảo trang web, sự hiện diện tìm kiếm và một kế hoạch để mang về nhiều khách hơn — không áp lực.', tl:'Pumili ng oras at iguguhit namin ang iyong site, ang search presence mo, at isang plano para sa mas maraming customer — walang presyur.', fr:'Choisissez un créneau et nous esquisserons votre site, votre présence en ligne et un plan pour vous amener plus de clients — sans engagement.', ar:'اختر وقتًا وسنرسم موقعك وحضورك في البحث وخطة لجلب المزيد من العملاء — دون أي ضغط.' },
    'Pick a time →': { es:'Elegir un horario →', zh:'选择时间 →', vi:'Chọn thời gian →', tl:'Pumili ng oras →', fr:'Choisir un créneau →', ar:'اختر وقتًا →' },
    'Reserve your build': { es:'Reserva tu proyecto', zh:'预订你的项目', vi:'Giữ chỗ dự án của bạn', tl:'I-reserve ang iyong build', fr:'Réservez votre projet', ar:'احجز مشروعك' },
    'Ready to roll? Put down your onboarding deposit and we\'ll start this week. It\'s applied straight to your project.': { es:'¿Listo para arrancar? Deja tu depósito de incorporación y empezamos esta semana. Se aplica directo a tu proyecto.', zh:'准备好了吗？支付启动定金，我们本周就开始。定金将直接抵扣到你的项目。', vi:'Sẵn sàng chưa? Đặt cọc khởi tạo và chúng tôi sẽ bắt đầu trong tuần này. Khoản này được trừ thẳng vào dự án của bạn.', tl:'Handa na? Maglagay ng onboarding deposit at magsisimula kami ngayong linggo. Ibabawas ito mismo sa proyekto mo.', fr:'Prêt à démarrer ? Versez votre acompte d’intégration et nous commençons cette semaine. Il est déduit directement de votre projet.', ar:'مستعدّ للانطلاق؟ ادفع عربون البدء وسنبدأ هذا الأسبوع. يُحتسب مباشرة ضمن مشروعك.' },
    'Start now →': { es:'Empezar ahora →', zh:'立即开始 →', vi:'Bắt đầu ngay →', tl:'Magsimula na →', fr:'Commencer maintenant →', ar:'ابدأ الآن →' },

    // ---- cookie ----
    'Decline': { es:'Rechazar', zh:'拒绝', vi:'Từ chối', tl:'Tanggihan', fr:'Refuser', ar:'رفض' },
    'Accept': { es:'Aceptar', zh:'接受', vi:'Chấp nhận', tl:'Tanggapin', fr:'Accepter', ar:'قبول' },

    // ---- misc ----
    'Get a free audit': { es:'Auditoría gratis', zh:'免费诊断', vi:'Nhận đánh giá miễn phí', tl:'Libreng audit', fr:'Audit gratuit', ar:'تدقيق مجاني' },
    'Search': { es:'Buscar', zh:'搜索', vi:'Tìm kiếm', tl:'Maghanap', fr:'Rechercher', ar:'بحث' },
    'Your Business': { es:'Tu Negocio', zh:'你的企业', vi:'Doanh nghiệp của bạn', tl:'Ang Negosyo Mo', fr:'Votre entreprise', ar:'نشاطك التجاري' },
    'Found ✓': { es:'Encontrado ✓', zh:'已找到 ✓', vi:'Đã tìm thấy ✓', tl:'Nahanap ✓', fr:'Trouvé ✓', ar:'✓ تم العثور' },
    'A competitor with an old site': { es:'Un competidor con un sitio viejo', zh:'一个使用旧网站的竞争对手', vi:'Một đối thủ với trang web cũ', tl:'Isang kakumpitensyang may lumang site', fr:'Un concurrent avec un vieux site', ar:'منافس بموقع قديم' },
    'Another generic listing': { es:'Otra ficha genérica', zh:'另一个普通商家', vi:'Một danh sách chung chung khác', tl:'Isa pang generic na listing', fr:'Une autre fiche générique', ar:'بطاقة عامة أخرى' },
    '⭐ 5.0 (128) · Open now · 2 mi away': { es:'⭐ 5.0 (128) · Abierto ahora · a 2 mi', zh:'⭐ 5.0（128）· 营业中 · 2 英里', vi:'⭐ 5.0 (128) · Đang mở cửa · cách 2 dặm', tl:'⭐ 5.0 (128) · Bukas ngayon · 2 mi ang layo', fr:'⭐ 5.0 (128) · Ouvert · à 2 mi', ar:'⭐ 5.0 (128) · مفتوح الآن · على بُعد ميلين' },
    '★ 4.1 · 12 mi': { es:'★ 4.1 · a 12 mi', zh:'★ 4.1 · 12 英里', vi:'★ 4.1 · cách 12 dặm', tl:'★ 4.1 · 12 mi', fr:'★ 4.1 · à 12 mi', ar:'★ 4.1 · على بُعد 12 ميلاً' },
    '★ 3.8 · 15 mi': { es:'★ 3.8 · a 15 mi', zh:'★ 3.8 · 15 英里', vi:'★ 3.8 · cách 15 dặm', tl:'★ 3.8 · 15 mi', fr:'★ 3.8 · à 15 mi', ar:'★ 3.8 · على بُعد 15 ميلاً' },

    // ---- hero trust + statband + service-card demos ----
    'Days to launch': { es:'<b class="grad-text">Días</b> para lanzar', zh:'<b class="grad-text">数天</b>即可上线', vi:'<b class="grad-text">Vài ngày</b> để ra mắt', tl:'<b class="grad-text">Mga araw</b> bago mag-launch', fr:'<b class="grad-text">Quelques jours</b> pour lancer', ar:'<b class="grad-text">أيام</b> للإطلاق' },
    '100% custom-built': { es:'<b class="grad-text">100%</b> a medida', zh:'<b class="grad-text">100%</b> 纯定制', vi:'<b class="grad-text">100%</b> tùy chỉnh', tl:'<b class="grad-text">100%</b> custom na gawa', fr:'<b class="grad-text">100%</b> sur mesure', ar:'<b class="grad-text">100%</b> مخصّص بالكامل' },
    'Google + AI optimized': { es:'<b class="grad-text">Google + IA</b> optimizado', zh:'<b class="grad-text">Google + AI</b> 优化', vi:'<b class="grad-text">Google + AI</b> tối ưu', tl:'<b class="grad-text">Google + AI</b> optimisado', fr:'<b class="grad-text">Google + IA</b> optimisé', ar:'<b class="grad-text">Google + ذكاء اصطناعي</b> مُحسّن' },
    'Flexible': { es:'Flexible', zh:'灵活', vi:'Linh hoạt', tl:'Nababaluktot', fr:'Flexible', ar:'مرن' },
    'yourbusiness.com': { es:'tunegocio.com', zh:'你的公司.com', vi:'doanhnghiepcuaban.com', tl:'angnegosyomo.com', fr:'votreentreprise.com', ar:'موقعك.com' },
    '✦ AI Search': { es:'<span class="svc-spark">✦</span> Búsqueda con IA', zh:'<span class="svc-spark">✦</span> AI 搜索', vi:'<span class="svc-spark">✦</span> Tìm kiếm AI', tl:'<span class="svc-spark">✦</span> AI Search', fr:'<span class="svc-spark">✦</span> Recherche IA', ar:'<span class="svc-spark">✦</span> بحث الذكاء الاصطناعي' },
    'best plumber near me?': { es:'¿mejor plomero cerca de mí?', zh:'附近最好的水管工？', vi:'thợ sửa ống nước tốt nhất gần đây?', tl:'pinakamahusay na plumber malapit?', fr:'meilleur plombier près de moi ?', ar:'أفضل سبّاك بالقرب مني؟' },
    'Acme Plumbing, top-rated & open now ✓': { es:'<b>Acme Plumbing</b>, mejor valorada y abierta ahora ✓', zh:'<b>Acme Plumbing</b>，评价最高且正在营业 ✓', vi:'<b>Acme Plumbing</b>, được đánh giá cao & đang mở cửa ✓', tl:'<b>Acme Plumbing</b>, top-rated at bukas ngayon ✓', fr:'<b>Acme Plumbing</b>, mieux notée et ouverte ✓', ar:'<b>Acme Plumbing</b>، الأعلى تقييمًا ومفتوحة الآن ✓' },
    'Your Business ✓': { es:'Tu Negocio <span class="svg-verified">✓</span>', zh:'你的企业 <span class="svg-verified">✓</span>', vi:'Doanh nghiệp của bạn <span class="svg-verified">✓</span>', tl:'Ang Negosyo Mo <span class="svg-verified">✓</span>', fr:'Votre entreprise <span class="svg-verified">✓</span>', ar:'نشاطك التجاري <span class="svg-verified">✓</span>' },
    '★★★★★ "Fantastic service. Highly recommend!"': { es:'★★★★★ «Servicio fantástico. ¡Muy recomendado!»', zh:'★★★★★ “服务太棒了。强烈推荐！”', vi:'★★★★★ “Dịch vụ tuyệt vời. Rất đáng giới thiệu!”', tl:'★★★★★ “Napakaganda ng serbisyo. Highly recommend!”', fr:'★★★★★ « Service fantastique. Je recommande vivement ! »', ar:'★★★★★ ”خدمة رائعة. أنصح بها بشدّة!“' }
  };

  // Localized rotating search phrases for the hero demo (exposed to the hero typing script).
  var PHRASES = {
    en: ['best plumber near me', 'steam cleaning near me', 'web design company', 'auto repair open now', 'top rated electrician'],
    es: ['mejor plomero cerca de mí', 'limpieza a vapor cerca de mí', 'empresa de diseño web', 'taller mecánico abierto ahora', 'electricista mejor valorado'],
    zh: ['附近最好的水管工', '附近的蒸汽清洗', '网页设计公司', '现在营业的汽车维修', '评价最高的电工'],
    vi: ['thợ sửa ống nước tốt nhất gần đây', 'giặt hơi nước gần đây', 'công ty thiết kế web', 'sửa xe đang mở cửa', 'thợ điện được đánh giá cao nhất'],
    tl: ['pinakamahusay na plumber malapit', 'steam cleaning malapit sa akin', 'kompanya ng web design', 'auto repair bukas ngayon', 'top rated na electrician'],
    fr: ['meilleur plombier près de moi', 'nettoyage vapeur près de moi', 'agence de création de site', 'garage auto ouvert maintenant', 'électricien le mieux noté'],
    ar: ['أفضل سبّاك بالقرب مني', 'تنظيف بالبخار قريب مني', 'شركة تصميم مواقع', 'تصليح سيارات مفتوح الآن', 'أفضل كهربائي تقييمًا']
  };

  function norm(s) { return (s || '').replace(/\s+/g, ' ').trim().replace(/[‘’]/g, "'").replace(/[“”]/g, '"'); }
  var SEL = 'nav.nav-links a, .nav-cta a, .hero-actions a, .eyebrow, h1, h2, h3, .hero .sub, .optfor .lbl, .prob h4, .prob p, .card p, .statband .l, .step h4, .step p, .vtag, .sec-head p, .cta-band p, .lead-form button, #form-msg, #cookie-banner button, .result .rname, .result .rmeta, .result .pill, .searchbar .go, .hero-trust div, .value p, .manifesto p, .cmp th, .cmp td, .svb-bar span, .svc-head, .svc-q, .svc-a, .svg-name, .svg-rev, .start-card h3, .start-card p, .start-card .btn, .pstat, .statband .n, .step .num, .quote p, .promise span, #cookie-banner p, footer a, .pk-name, .pk-tag, .pk-build, .pk-mo, .pkg li, .pkg .btn, .pkg-note, .addon-head p, .addon h4, .addon p, .ad-price, .ad-add';
  var store = null;
  function collect() {
    store = [];
    document.querySelectorAll(SEL).forEach(function (el) {
      store.push({ el: el, html: el.innerHTML, key: norm(el.textContent) });
    });
  }
  function apply(lang) {
    if (!store) collect();
    store.forEach(function (s) {
      if (lang === 'en') { s.el.innerHTML = s.html; return; }
      var e = T[s.key];
      s.el.innerHTML = (e && e[lang]) ? e[lang] : s.html;
    });
    document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(function (el) {
      if (el.__ph == null) el.__ph = el.getAttribute('placeholder');
      var e = T[norm(el.__ph)];
      el.setAttribute('placeholder', (lang !== 'en' && e && e[lang]) ? e[lang] : el.__ph);
    });
    var L = LANGS.filter(function (x) { return x.code === lang; })[0] || LANGS[0];
    document.documentElement.lang = lang;
    document.documentElement.dir = L.dir;
    try { localStorage.setItem('rr_lang', lang); } catch (e) {}
    window.__rrPhrases = PHRASES[lang] || PHRASES.en;
    try { window.dispatchEvent(new CustomEvent('rr-lang')); } catch (e) {}
    var u = new URL(location.href); if (lang === 'en') u.searchParams.delete('lang'); else u.searchParams.set('lang', lang);
    history.replaceState(null, '', u);
    var cur = document.getElementById('rr-lang-cur'); if (cur) cur.textContent = L.native;
    document.querySelectorAll('#rr-lang-menu button').forEach(function (b) { b.setAttribute('aria-current', b.dataset.code === lang ? 'true' : 'false'); });
  }

  function buildSwitcher() {
    var mount = document.getElementById('langpick'); if (!mount) return;
    var cur = currentLang();
    var curNative = (LANGS.filter(function (x) { return x.code === cur; })[0] || LANGS[0]).native;
    mount.innerHTML =
      '<button id="rr-lang-btn" aria-haspopup="true" aria-expanded="false">🌐 <span id="rr-lang-cur">' + curNative + '</span> ▾</button>' +
      '<div id="rr-lang-menu" role="menu">' + LANGS.map(function (l) {
        return '<button role="menuitem" data-code="' + l.code + '"' + (l.dir === 'rtl' ? ' dir="rtl"' : '') + '>' + l.native + '</button>';
      }).join('') + '</div>';
    var btn = document.getElementById('rr-lang-btn'), menu = document.getElementById('rr-lang-menu');
    btn.addEventListener('click', function (e) { e.stopPropagation(); var open = menu.classList.toggle('open'); btn.setAttribute('aria-expanded', open ? 'true' : 'false'); });
    document.addEventListener('click', function () { menu.classList.remove('open'); btn.setAttribute('aria-expanded', 'false'); });
    menu.querySelectorAll('button').forEach(function (b) { b.addEventListener('click', function () { apply(b.dataset.code); menu.classList.remove('open'); }); });
  }

  function currentLang() {
    var q = new URL(location.href).searchParams.get('lang');
    if (q && LANGS.some(function (l) { return l.code === q; })) return q;
    try { var s = localStorage.getItem('rr_lang'); if (s && LANGS.some(function (l) { return l.code === s; })) return s; } catch (e) {}
    var nav = (navigator.language || 'en').slice(0, 2).toLowerCase();
    return LANGS.some(function (l) { return l.code === nav; }) ? nav : 'en';
  }

  function init() { collect(); buildSwitcher(); apply(currentLang()); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
})();
